CREATE TABLE rs_table_11_0 AS SELECT "t1"."c_customer_id" AS "customer_id", "t1"."c_first_name" AS "customer_first_name", "t1"."c_last_name" AS "customer_last_name", "t1"."c_preferred_cust_flag" AS "customer_preferred_cust_flag", "t1"."c_birth_country" AS "customer_birth_country", "t1"."c_login" AS "customer_login", "t1"."c_email_address" AS "customer_email_address", "t2"."d_year" AS "dyear", SUM("t1"."-") AS "year_total", 's' AS "sale_type"
FROM (SELECT "t"."c_customer_id", "t"."c_first_name", "t"."c_last_name", "t"."c_preferred_cust_flag", "t"."c_birth_country", "t"."c_login", "t"."c_email_address", "t0"."ss_sold_date_sk", "t0"."-"
FROM (SELECT "c_customer_sk", "c_customer_id", "c_first_name", "c_last_name", "c_preferred_cust_flag", "c_birth_country", "c_login", "c_email_address"
FROM customer) AS "t"
INNER JOIN (SELECT "ss_sold_date_sk", "ss_customer_sk", "ss_ext_list_price" - "ss_ext_discount_amt" AS "-"
FROM store_sales) AS "t0" ON "t"."c_customer_sk" = "t0"."ss_customer_sk") AS "t1"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM date_dim) AS "t2" ON "t1"."ss_sold_date_sk" = "t2"."d_date_sk"
GROUP BY "t1"."c_customer_id", "t1"."c_first_name", "t1"."c_last_name", "t1"."c_preferred_cust_flag", "t1"."c_birth_country", "t1"."c_login", "t1"."c_email_address", "t2"."d_year"
UNION ALL
SELECT "t8"."c_customer_id" AS "customer_id", "t8"."c_first_name" AS "customer_first_name", "t8"."c_last_name" AS "customer_last_name", "t8"."c_preferred_cust_flag" AS "customer_preferred_cust_flag", "t8"."c_birth_country" AS "customer_birth_country", "t8"."c_login" AS "customer_login", "t8"."c_email_address" AS "customer_email_address", "t9"."d_year" AS "dyear", SUM("t8"."-") AS "year_total", 'w' AS "sale_type"
FROM (SELECT "t6"."c_customer_id", "t6"."c_first_name", "t6"."c_last_name", "t6"."c_preferred_cust_flag", "t6"."c_birth_country", "t6"."c_login", "t6"."c_email_address", "t7"."ws_sold_date_sk", "t7"."-"
FROM (SELECT "c_customer_sk", "c_customer_id", "c_first_name", "c_last_name", "c_preferred_cust_flag", "c_birth_country", "c_login", "c_email_address"
FROM customer) AS "t6"
INNER JOIN (SELECT "ws_sold_date_sk", "ws_bill_customer_sk", "ws_ext_list_price" - "ws_ext_discount_amt" AS "-"
FROM web_sales) AS "t7" ON "t6"."c_customer_sk" = "t7"."ws_bill_customer_sk") AS "t8"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM date_dim) AS "t9" ON "t8"."ws_sold_date_sk" = "t9"."d_date_sk"
GROUP BY "t8"."c_customer_id", "t8"."c_first_name", "t8"."c_last_name", "t8"."c_preferred_cust_flag", "t8"."c_birth_country", "t8"."c_login", "t8"."c_email_address", "t9"."d_year"
;
CREATE TABLE rs_table_11_1 AS SELECT "t1"."customer_id", "t4"."customer_id" AS "customer_id0", "t4"."customer_first_name" AS "customer_first_name0", "t4"."customer_last_name" AS "customer_last_name0", "t4"."customer_preferred_cust_flag" AS "customer_preferred_cust_flag0", "t1".">", "t4"."""*""" / "t1"."year_total" AS "/"
FROM (SELECT "customer_id", "year_total", "year_total" > 0 AS ">"
FROM "rs_table_11_0"
WHERE "sale_type" = 's' AND "dyear" = 2001 AND "year_total" > 0) AS "t1"
INNER JOIN (SELECT "customer_id", "customer_first_name", "customer_last_name", "customer_preferred_cust_flag", "year_total" * 1.0000 AS """*"""
FROM "rs_table_11_0"
WHERE "sale_type" = 's' AND "dyear" = 2001 + 1) AS "t4" ON "t1"."customer_id" = "t4"."customer_id"
;
SELECT "t18"."customer_id0" AS "customer_id", "t18"."customer_first_name0" AS "customer_first_name", "t18"."customer_last_name0" AS "customer_last_name", "t18"."customer_preferred_cust_flag0" AS "customer_preferred_cust_flag"
FROM (SELECT "rs_table_11_1"."customer_id", "rs_table_11_1"."customer_id0", "rs_table_11_1"."customer_first_name0", "rs_table_11_1"."customer_last_name0", "rs_table_11_1"."customer_preferred_cust_flag0", "t16"."year_total" AS "year_total1", "t16".">", CASE WHEN "rs_table_11_1".">" THEN "rs_table_11_1"."/" ELSE 0.0 END AS "CASE"
FROM "rs_table_11_1"
INNER JOIN (SELECT "customer_id", "year_total", "year_total" > 0 AS ">"
FROM (SELECT "t1"."c_customer_id" AS "customer_id", "t1"."c_first_name" AS "customer_first_name", "t1"."c_last_name" AS "customer_last_name", "t1"."c_preferred_cust_flag" AS "customer_preferred_cust_flag", "t1"."c_birth_country" AS "customer_birth_country", "t1"."c_login" AS "customer_login", "t1"."c_email_address" AS "customer_email_address", "t2"."d_year" AS "dyear", SUM("t1"."-") AS "year_total", 's' AS "sale_type"
FROM (SELECT "t"."c_customer_id", "t"."c_first_name", "t"."c_last_name", "t"."c_preferred_cust_flag", "t"."c_birth_country", "t"."c_login", "t"."c_email_address", "t0"."ss_sold_date_sk", "t0"."-"
FROM (SELECT "c_customer_sk", "c_customer_id", "c_first_name", "c_last_name", "c_preferred_cust_flag", "c_birth_country", "c_login", "c_email_address"
FROM customer) AS "t"
INNER JOIN (SELECT "ss_sold_date_sk", "ss_customer_sk", "ss_ext_list_price" - "ss_ext_discount_amt" AS "-"
FROM store_sales) AS "t0" ON "t"."c_customer_sk" = "t0"."ss_customer_sk") AS "t1"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM date_dim) AS "t2" ON "t1"."ss_sold_date_sk" = "t2"."d_date_sk"
GROUP BY "t1"."c_customer_id", "t1"."c_first_name", "t1"."c_last_name", "t1"."c_preferred_cust_flag", "t1"."c_birth_country", "t1"."c_login", "t1"."c_email_address", "t2"."d_year"
UNION ALL
SELECT "t8"."c_customer_id" AS "customer_id", "t8"."c_first_name" AS "customer_first_name", "t8"."c_last_name" AS "customer_last_name", "t8"."c_preferred_cust_flag" AS "customer_preferred_cust_flag", "t8"."c_birth_country" AS "customer_birth_country", "t8"."c_login" AS "customer_login", "t8"."c_email_address" AS "customer_email_address", "t9"."d_year" AS "dyear", SUM("t8"."-") AS "year_total", 'w' AS "sale_type"
FROM (SELECT "t6"."c_customer_id", "t6"."c_first_name", "t6"."c_last_name", "t6"."c_preferred_cust_flag", "t6"."c_birth_country", "t6"."c_login", "t6"."c_email_address", "t7"."ws_sold_date_sk", "t7"."-"
FROM (SELECT "c_customer_sk", "c_customer_id", "c_first_name", "c_last_name", "c_preferred_cust_flag", "c_birth_country", "c_login", "c_email_address"
FROM customer) AS "t6"
INNER JOIN (SELECT "ws_sold_date_sk", "ws_bill_customer_sk", "ws_ext_list_price" - "ws_ext_discount_amt" AS "-"
FROM web_sales) AS "t7" ON "t6"."c_customer_sk" = "t7"."ws_bill_customer_sk") AS "t8"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM date_dim) AS "t9" ON "t8"."ws_sold_date_sk" = "t9"."d_date_sk"
GROUP BY "t8"."c_customer_id", "t8"."c_first_name", "t8"."c_last_name", "t8"."c_preferred_cust_flag", "t8"."c_birth_country", "t8"."c_login", "t8"."c_email_address", "t9"."d_year") AS "t13"
WHERE "sale_type" = 'w' AND "dyear" = 2001 AND "year_total" > 0) AS "t16" ON "rs_table_11_1"."customer_id" = "t16"."customer_id") AS "t18"
INNER JOIN (SELECT "customer_id", "year_total" * 1.0000 AS """*"""
FROM (SELECT "t21"."c_customer_id" AS "customer_id", "t21"."c_first_name" AS "customer_first_name", "t21"."c_last_name" AS "customer_last_name", "t21"."c_preferred_cust_flag" AS "customer_preferred_cust_flag", "t21"."c_birth_country" AS "customer_birth_country", "t21"."c_login" AS "customer_login", "t21"."c_email_address" AS "customer_email_address", "t22"."d_year" AS "dyear", SUM("t21"."-") AS "year_total", 's' AS "sale_type"
FROM (SELECT "t19"."c_customer_id", "t19"."c_first_name", "t19"."c_last_name", "t19"."c_preferred_cust_flag", "t19"."c_birth_country", "t19"."c_login", "t19"."c_email_address", "t20"."ss_sold_date_sk", "t20"."-"
FROM (SELECT "c_customer_sk", "c_customer_id", "c_first_name", "c_last_name", "c_preferred_cust_flag", "c_birth_country", "c_login", "c_email_address"
FROM customer) AS "t19"
INNER JOIN (SELECT "ss_sold_date_sk", "ss_customer_sk", "ss_ext_list_price" - "ss_ext_discount_amt" AS "-"
FROM store_sales) AS "t20" ON "t19"."c_customer_sk" = "t20"."ss_customer_sk") AS "t21"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM date_dim) AS "t22" ON "t21"."ss_sold_date_sk" = "t22"."d_date_sk"
GROUP BY "t21"."c_customer_id", "t21"."c_first_name", "t21"."c_last_name", "t21"."c_preferred_cust_flag", "t21"."c_birth_country", "t21"."c_login", "t21"."c_email_address", "t22"."d_year"
UNION ALL
SELECT "t28"."c_customer_id" AS "customer_id", "t28"."c_first_name" AS "customer_first_name", "t28"."c_last_name" AS "customer_last_name", "t28"."c_preferred_cust_flag" AS "customer_preferred_cust_flag", "t28"."c_birth_country" AS "customer_birth_country", "t28"."c_login" AS "customer_login", "t28"."c_email_address" AS "customer_email_address", "t29"."d_year" AS "dyear", SUM("t28"."-") AS "year_total", 'w' AS "sale_type"
FROM (SELECT "t26"."c_customer_id", "t26"."c_first_name", "t26"."c_last_name", "t26"."c_preferred_cust_flag", "t26"."c_birth_country", "t26"."c_login", "t26"."c_email_address", "t27"."ws_sold_date_sk", "t27"."-"
FROM (SELECT "c_customer_sk", "c_customer_id", "c_first_name", "c_last_name", "c_preferred_cust_flag", "c_birth_country", "c_login", "c_email_address"
FROM customer) AS "t26"
INNER JOIN (SELECT "ws_sold_date_sk", "ws_bill_customer_sk", "ws_ext_list_price" - "ws_ext_discount_amt" AS "-"
FROM web_sales) AS "t27" ON "t26"."c_customer_sk" = "t27"."ws_bill_customer_sk") AS "t28"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM date_dim) AS "t29" ON "t28"."ws_sold_date_sk" = "t29"."d_date_sk"
GROUP BY "t28"."c_customer_id", "t28"."c_first_name", "t28"."c_last_name", "t28"."c_preferred_cust_flag", "t28"."c_birth_country", "t28"."c_login", "t28"."c_email_address", "t29"."d_year") AS "t33"
WHERE "sale_type" = 'w' AND "dyear" = 2001 + 1) AS "t36" ON "t18"."customer_id" = "t36"."customer_id" AND CASE WHEN "t18".">" THEN "t36"."""*""" / "t18"."year_total1" ELSE 0.0 END > "t18"."CASE"
ORDER BY "t18"."customer_id0" NULLS FIRST, "t18"."customer_first_name0" NULLS FIRST, "t18"."customer_last_name0" NULLS FIRST, "t18"."customer_preferred_cust_flag0" NULLS FIRST
LIMIT 100
;
