create table catalog_returns(
	cr_returned_date_sk integer,
	cr_returned_time_sk integer,
	cr_item_sk integer not null,
	cr_refunded_customer_sk integer,
	cr_refunded_cdemo_sk integer,
	cr_refunded_hdemo_sk integer,
	cr_refunded_addr_sk integer,
	cr_returning_customer_sk integer,
	cr_returning_cdemo_sk integer,
	cr_returning_hdemo_sk integer,
	cr_returning_addr_sk integer,
	cr_call_center_sk integer,
	cr_catalog_page_sk integer,
	cr_ship_mode_sk integer,
	cr_warehouse_sk integer,
	cr_reason_sk integer,
	cr_order_number integer not null,
	cr_return_quantity integer,
	cr_return_amount double precision,
	cr_return_tax double precision,
	cr_return_amt_inc_tax double precision,
	cr_fee double precision,
	cr_return_ship_cost double precision,
	cr_refunded_cash double precision,
	cr_reversed_charge double precision,
	cr_store_credit double precision,
	cr_net_loss double precision
);
