SELECT "w_warehouse_name", "w_warehouse_sq_ft", "w_city", "w_county", "w_state", "w_country", "ship_carriers", "year_", SUM("jan_sales") AS "jan_sales", SUM("feb_sales") AS "feb_sales", SUM("mar_sales") AS "mar_sales", SUM("apr_sales") AS "apr_sales", SUM("may_sales") AS "may_sales", SUM("jun_sales") AS "jun_sales", SUM("jul_sales") AS "jul_sales", SUM("aug_sales") AS "aug_sales", SUM("sep_sales") AS "sep_sales", SUM("oct_sales") AS "oct_sales", SUM("nov_sales") AS "nov_sales", SUM("dec_sales") AS "dec_sales", SUM("jan_sales" / "w_warehouse_sq_ft") AS "jan_sales_per_sq_foot", SUM("feb_sales" / "w_warehouse_sq_ft") AS "feb_sales_per_sq_foot", SUM("mar_sales" / "w_warehouse_sq_ft") AS "mar_sales_per_sq_foot", SUM("apr_sales" / "w_warehouse_sq_ft") AS "apr_sales_per_sq_foot", SUM("may_sales" / "w_warehouse_sq_ft") AS "may_sales_per_sq_foot", SUM("jun_sales" / "w_warehouse_sq_ft") AS "jun_sales_per_sq_foot", SUM("jul_sales" / "w_warehouse_sq_ft") AS "jul_sales_per_sq_foot", SUM("aug_sales" / "w_warehouse_sq_ft") AS "aug_sales_per_sq_foot", SUM("sep_sales" / "w_warehouse_sq_ft") AS "sep_sales_per_sq_foot", SUM("oct_sales" / "w_warehouse_sq_ft") AS "oct_sales_per_sq_foot", SUM("nov_sales" / "w_warehouse_sq_ft") AS "nov_sales_per_sq_foot", SUM("dec_sales" / "w_warehouse_sq_ft") AS "dec_sales_per_sq_foot", SUM("jan_net") AS "jan_net", SUM("feb_net") AS "feb_net", SUM("mar_net") AS "mar_net", SUM("apr_net") AS "apr_net", SUM("may_net") AS "may_net", SUM("jun_net") AS "jun_net", SUM("jul_net") AS "jul_net", SUM("aug_net") AS "aug_net", SUM("sep_net") AS "sep_net", SUM("oct_net") AS "oct_net", SUM("nov_net") AS "nov_net", SUM("dec_net") AS "dec_net"
FROM (SELECT "t10"."w_warehouse_name", "t10"."w_warehouse_sq_ft", "t10"."w_city", "t10"."w_county", "t10"."w_state", "t10"."w_country", 'DHL,BARIAN' AS "ship_carriers", "t10"."d_year" AS "year_", SUM("t10"."CASE") AS "jan_sales", SUM("t10"."CASE9") AS "feb_sales", SUM("t10"."CASE10") AS "mar_sales", SUM("t10"."CASE11") AS "apr_sales", SUM("t10"."CASE12") AS "may_sales", SUM("t10"."CASE13") AS "jun_sales", SUM("t10"."CASE14") AS "jul_sales", SUM("t10"."CASE15") AS "aug_sales", SUM("t10"."CASE16") AS "sep_sales", SUM("t10"."CASE17") AS "oct_sales", SUM("t10"."CASE18") AS "nov_sales", SUM("t10"."CASE19") AS "dec_sales", SUM("t10"."CASE20") AS "jan_net", SUM("t10"."CASE21") AS "feb_net", SUM("t10"."CASE22") AS "mar_net", SUM("t10"."CASE23") AS "apr_net", SUM("t10"."CASE24") AS "may_net", SUM("t10"."CASE25") AS "jun_net", SUM("t10"."CASE26") AS "jul_net", SUM("t10"."CASE27") AS "aug_net", SUM("t10"."CASE28") AS "sep_net", SUM("t10"."CASE29") AS "oct_net", SUM("t10"."CASE30") AS "nov_net", SUM("t10"."CASE31") AS "dec_net"
FROM (SELECT "t5"."ws_ship_mode_sk", "t5"."w_warehouse_name", "t5"."w_warehouse_sq_ft", "t5"."w_city", "t5"."w_county", "t5"."w_state", "t5"."w_country", "t5"."d_year", CASE WHEN "t5"."=" THEN "t5"."""*""" ELSE 0 END AS "CASE", CASE WHEN "t5"."=11" THEN "t5"."""*""" ELSE 0 END AS "CASE9", CASE WHEN "t5"."=12" THEN "t5"."""*""" ELSE 0 END AS "CASE10", CASE WHEN "t5"."=13" THEN "t5"."""*""" ELSE 0 END AS "CASE11", CASE WHEN "t5"."=14" THEN "t5"."""*""" ELSE 0 END AS "CASE12", CASE WHEN "t5"."=15" THEN "t5"."""*""" ELSE 0 END AS "CASE13", CASE WHEN "t5"."=16" THEN "t5"."""*""" ELSE 0 END AS "CASE14", CASE WHEN "t5"."=17" THEN "t5"."""*""" ELSE 0 END AS "CASE15", CASE WHEN "t5"."=18" THEN "t5"."""*""" ELSE 0 END AS "CASE16", CASE WHEN "t5"."=19" THEN "t5"."""*""" ELSE 0 END AS "CASE17", CASE WHEN "t5"."=20" THEN "t5"."""*""" ELSE 0 END AS "CASE18", CASE WHEN "t5"."=21" THEN "t5"."""*""" ELSE 0 END AS "CASE19", CASE WHEN "t5"."=" THEN "t5"."*22" ELSE 0 END AS "CASE20", CASE WHEN "t5"."=11" THEN "t5"."*22" ELSE 0 END AS "CASE21", CASE WHEN "t5"."=12" THEN "t5"."*22" ELSE 0 END AS "CASE22", CASE WHEN "t5"."=13" THEN "t5"."*22" ELSE 0 END AS "CASE23", CASE WHEN "t5"."=14" THEN "t5"."*22" ELSE 0 END AS "CASE24", CASE WHEN "t5"."=15" THEN "t5"."*22" ELSE 0 END AS "CASE25", CASE WHEN "t5"."=16" THEN "t5"."*22" ELSE 0 END AS "CASE26", CASE WHEN "t5"."=17" THEN "t5"."*22" ELSE 0 END AS "CASE27", CASE WHEN "t5"."=18" THEN "t5"."*22" ELSE 0 END AS "CASE28", CASE WHEN "t5"."=19" THEN "t5"."*22" ELSE 0 END AS "CASE29", CASE WHEN "t5"."=20" THEN "t5"."*22" ELSE 0 END AS "CASE30", CASE WHEN "t5"."=21" THEN "t5"."*22" ELSE 0 END AS "CASE31"
FROM (SELECT "t1"."ws_sold_time_sk", "t1"."ws_ship_mode_sk", "t1"."w_warehouse_name", "t1"."w_warehouse_sq_ft", "t1"."w_city", "t1"."w_county", "t1"."w_state", "t1"."w_country", "t4"."d_year", "t4"."=", "t1"."""*""" AS """*""", "t4"."=3" AS "=11", "t4"."=4" AS "=12", "t4"."=5" AS "=13", "t4"."=6" AS "=14", "t4"."=7" AS "=15", "t4"."=8" AS "=16", "t4"."=9" AS "=17", "t4"."=10" AS "=18", "t4"."=11" AS "=19", "t4"."=12" AS "=20", "t4"."=13" AS "=21", "t1"."*10" AS "*22"
FROM (SELECT "t"."ws_sold_date_sk", "t"."ws_sold_time_sk", "t"."ws_ship_mode_sk", "t0"."w_warehouse_name", "t0"."w_warehouse_sq_ft", "t0"."w_city", "t0"."w_county", "t0"."w_state", "t0"."w_country", "t"."""*""" AS """*""", "t"."*5" AS "*10"
FROM (SELECT "ws_sold_date_sk", "ws_sold_time_sk", "ws_ship_mode_sk", "ws_warehouse_sk", "ws_ext_sales_price" * "ws_quantity" AS """*""", "ws_net_paid" * "ws_quantity" AS "*5"
FROM web_sales) AS "t"
INNER JOIN (SELECT "w_warehouse_sk", "w_warehouse_name", "w_warehouse_sq_ft", "w_city", "w_county", "w_state", "w_country"
FROM warehouse) AS "t0" ON "t"."ws_warehouse_sk" = "t0"."w_warehouse_sk") AS "t1"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_moy" = 1 AS "=", "d_moy" = 2 AS "=3", "d_moy" = 3 AS "=4", "d_moy" = 4 AS "=5", "d_moy" = 5 AS "=6", "d_moy" = 6 AS "=7", "d_moy" = 7 AS "=8", "d_moy" = 8 AS "=9", "d_moy" = 9 AS "=10", "d_moy" = 10 AS "=11", "d_moy" = 11 AS "=12", "d_moy" = 12 AS "=13"
FROM date_dim
WHERE "d_year" = 2001) AS "t4" ON "t1"."ws_sold_date_sk" = "t4"."d_date_sk") AS "t5"
INNER JOIN (SELECT "t_time_sk"
FROM time_dim
WHERE "t_time" >= 30838 AND "t_time" <= 30838 + 28800) AS "t8" ON "t5"."ws_sold_time_sk" = "t8"."t_time_sk") AS "t10"
INNER JOIN (SELECT "sm_ship_mode_sk"
FROM ship_mode
WHERE "sm_carrier" IN ('BARIAN', 'DHL')) AS "t13" ON "t10"."ws_ship_mode_sk" = "t13"."sm_ship_mode_sk"
GROUP BY "t10"."w_warehouse_name", "t10"."w_warehouse_sq_ft", "t10"."w_city", "t10"."w_county", "t10"."w_state", "t10"."w_country", "t10"."d_year"
UNION ALL
SELECT "t28"."w_warehouse_name", "t28"."w_warehouse_sq_ft", "t28"."w_city", "t28"."w_county", "t28"."w_state", "t28"."w_country", 'DHL,BARIAN' AS "ship_carriers", "t28"."d_year" AS "year_", SUM("t28"."CASE") AS "jan_sales", SUM("t28"."CASE9") AS "feb_sales", SUM("t28"."CASE10") AS "mar_sales", SUM("t28"."CASE11") AS "apr_sales", SUM("t28"."CASE12") AS "may_sales", SUM("t28"."CASE13") AS "jun_sales", SUM("t28"."CASE14") AS "jul_sales", SUM("t28"."CASE15") AS "aug_sales", SUM("t28"."CASE16") AS "sep_sales", SUM("t28"."CASE17") AS "oct_sales", SUM("t28"."CASE18") AS "nov_sales", SUM("t28"."CASE19") AS "dec_sales", SUM("t28"."CASE20") AS "jan_net", SUM("t28"."CASE21") AS "feb_net", SUM("t28"."CASE22") AS "mar_net", SUM("t28"."CASE23") AS "apr_net", SUM("t28"."CASE24") AS "may_net", SUM("t28"."CASE25") AS "jun_net", SUM("t28"."CASE26") AS "jul_net", SUM("t28"."CASE27") AS "aug_net", SUM("t28"."CASE28") AS "sep_net", SUM("t28"."CASE29") AS "oct_net", SUM("t28"."CASE30") AS "nov_net", SUM("t28"."CASE31") AS "dec_net"
FROM (SELECT "t23"."cs_ship_mode_sk", "t23"."w_warehouse_name", "t23"."w_warehouse_sq_ft", "t23"."w_city", "t23"."w_county", "t23"."w_state", "t23"."w_country", "t23"."d_year", CASE WHEN "t23"."=" THEN "t23"."""*""" ELSE 0 END AS "CASE", CASE WHEN "t23"."=11" THEN "t23"."""*""" ELSE 0 END AS "CASE9", CASE WHEN "t23"."=12" THEN "t23"."""*""" ELSE 0 END AS "CASE10", CASE WHEN "t23"."=13" THEN "t23"."""*""" ELSE 0 END AS "CASE11", CASE WHEN "t23"."=14" THEN "t23"."""*""" ELSE 0 END AS "CASE12", CASE WHEN "t23"."=15" THEN "t23"."""*""" ELSE 0 END AS "CASE13", CASE WHEN "t23"."=16" THEN "t23"."""*""" ELSE 0 END AS "CASE14", CASE WHEN "t23"."=17" THEN "t23"."""*""" ELSE 0 END AS "CASE15", CASE WHEN "t23"."=18" THEN "t23"."""*""" ELSE 0 END AS "CASE16", CASE WHEN "t23"."=19" THEN "t23"."""*""" ELSE 0 END AS "CASE17", CASE WHEN "t23"."=20" THEN "t23"."""*""" ELSE 0 END AS "CASE18", CASE WHEN "t23"."=21" THEN "t23"."""*""" ELSE 0 END AS "CASE19", CASE WHEN "t23"."=" THEN "t23"."*22" ELSE 0 END AS "CASE20", CASE WHEN "t23"."=11" THEN "t23"."*22" ELSE 0 END AS "CASE21", CASE WHEN "t23"."=12" THEN "t23"."*22" ELSE 0 END AS "CASE22", CASE WHEN "t23"."=13" THEN "t23"."*22" ELSE 0 END AS "CASE23", CASE WHEN "t23"."=14" THEN "t23"."*22" ELSE 0 END AS "CASE24", CASE WHEN "t23"."=15" THEN "t23"."*22" ELSE 0 END AS "CASE25", CASE WHEN "t23"."=16" THEN "t23"."*22" ELSE 0 END AS "CASE26", CASE WHEN "t23"."=17" THEN "t23"."*22" ELSE 0 END AS "CASE27", CASE WHEN "t23"."=18" THEN "t23"."*22" ELSE 0 END AS "CASE28", CASE WHEN "t23"."=19" THEN "t23"."*22" ELSE 0 END AS "CASE29", CASE WHEN "t23"."=20" THEN "t23"."*22" ELSE 0 END AS "CASE30", CASE WHEN "t23"."=21" THEN "t23"."*22" ELSE 0 END AS "CASE31"
FROM (SELECT "t19"."cs_sold_time_sk", "t19"."cs_ship_mode_sk", "t19"."w_warehouse_name", "t19"."w_warehouse_sq_ft", "t19"."w_city", "t19"."w_county", "t19"."w_state", "t19"."w_country", "t22"."d_year", "t22"."=", "t19"."""*""" AS """*""", "t22"."=3" AS "=11", "t22"."=4" AS "=12", "t22"."=5" AS "=13", "t22"."=6" AS "=14", "t22"."=7" AS "=15", "t22"."=8" AS "=16", "t22"."=9" AS "=17", "t22"."=10" AS "=18", "t22"."=11" AS "=19", "t22"."=12" AS "=20", "t22"."=13" AS "=21", "t19"."*10" AS "*22"
FROM (SELECT "t17"."cs_sold_date_sk", "t17"."cs_sold_time_sk", "t17"."cs_ship_mode_sk", "t18"."w_warehouse_name", "t18"."w_warehouse_sq_ft", "t18"."w_city", "t18"."w_county", "t18"."w_state", "t18"."w_country", "t17"."""*""" AS """*""", "t17"."*5" AS "*10"
FROM (SELECT "cs_sold_date_sk", "cs_sold_time_sk", "cs_ship_mode_sk", "cs_warehouse_sk", "cs_sales_price" * "cs_quantity" AS """*""", "cs_net_paid_inc_tax" * "cs_quantity" AS "*5"
FROM catalog_sales) AS "t17"
INNER JOIN (SELECT "w_warehouse_sk", "w_warehouse_name", "w_warehouse_sq_ft", "w_city", "w_county", "w_state", "w_country"
FROM warehouse) AS "t18" ON "t17"."cs_warehouse_sk" = "t18"."w_warehouse_sk") AS "t19"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_moy" = 1 AS "=", "d_moy" = 2 AS "=3", "d_moy" = 3 AS "=4", "d_moy" = 4 AS "=5", "d_moy" = 5 AS "=6", "d_moy" = 6 AS "=7", "d_moy" = 7 AS "=8", "d_moy" = 8 AS "=9", "d_moy" = 9 AS "=10", "d_moy" = 10 AS "=11", "d_moy" = 11 AS "=12", "d_moy" = 12 AS "=13"
FROM date_dim
WHERE "d_year" = 2001) AS "t22" ON "t19"."cs_sold_date_sk" = "t22"."d_date_sk") AS "t23"
INNER JOIN (SELECT "t_time_sk"
FROM time_dim
WHERE "t_time" >= 30838 AND "t_time" <= 30838 + 28800) AS "t26" ON "t23"."cs_sold_time_sk" = "t26"."t_time_sk") AS "t28"
INNER JOIN (SELECT "sm_ship_mode_sk"
FROM ship_mode
WHERE "sm_carrier" IN ('BARIAN', 'DHL')) AS "t31" ON "t28"."cs_ship_mode_sk" = "t31"."sm_ship_mode_sk"
GROUP BY "t28"."w_warehouse_name", "t28"."w_warehouse_sq_ft", "t28"."w_city", "t28"."w_county", "t28"."w_state", "t28"."w_country", "t28"."d_year") AS "t35"
GROUP BY "w_warehouse_name", "w_warehouse_sq_ft", "w_city", "w_county", "w_state", "w_country", "ship_carriers", "year_"
ORDER BY "w_warehouse_name" NULLS FIRST
LIMIT 100

