CREATE TABLE duck_table_31_0 AS SELECT "t2"."ca_county", SUM("t1"."ws_ext_sales_price") AS "web_sales", SUM("t1"."ws_ext_sales_price") * 1.0000 AS "*", SUM("t1"."ws_ext_sales_price") > 0 AS ">"
FROM (SELECT "t"."ws_bill_addr_sk", "t"."ws_ext_sales_price", "t0"."d_year", "t0"."d_qoy"
FROM (SELECT "ws_sold_date_sk", "ws_bill_addr_sk", "ws_ext_sales_price"
FROM '/mnt/disks/tpcds/parquet/web_sales.parquet' AS web_sales) AS "t"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t0" ON "t"."ws_sold_date_sk" = "t0"."d_date_sk") AS "t1"
INNER JOIN (SELECT "ca_address_sk", "ca_county"
FROM '/mnt/disks/tpcds/parquet/customer_address.parquet' AS customer_address) AS "t2" ON "t1"."ws_bill_addr_sk" = "t2"."ca_address_sk"
GROUP BY "t2"."ca_county", "t1"."d_qoy", "t1"."d_year"
HAVING "t1"."d_qoy" = 2 AND "t1"."d_year" = 2000;
SELECT "t35"."ca_county", "t35"."d_year", "t35"."/" AS "web_q1_q2_increase", "t35"."/5" AS "store_q1_q2_increase", "t43"."*" / "t35"."web_sales0" AS "web_q2_q3_increase", "t35"."/6" AS "store_q2_q3_increase"
FROM (SELECT "t33"."ca_county", "t33"."d_year", "t33"."ca_county2", "duck_table_31_0"."web_sales" AS "web_sales0", "duck_table_31_0"."*" / "t33"."web_sales" AS "/", "t33"."/" AS "/5", "t33"."/5" AS "/6", "duck_table_31_0".">", "t33"."CASE"
FROM (SELECT "t24"."ca_county", "t24"."d_year", "t32"."ca_county" AS "ca_county2", "t32"."web_sales", "t24"."/", "t24"."/3" AS "/5", "t24"."CASE", "t32".">", "t24"."CASE5" AS "CASE8"
FROM (SELECT "t15"."ca_county", "t15"."d_year", "t15"."/", "t23"."*" / "t15"."store_sales0" AS "/3", CASE WHEN "t15".">" THEN "t23"."*" / "t15"."store_sales0" ELSE NULL END AS "CASE", "t15"."CASE" AS "CASE5"
FROM (SELECT "t6"."ca_county", "t6"."d_year", "t14"."ca_county" AS "ca_county0", "t14"."store_sales" AS "store_sales0", "t14"."*" / "t6"."store_sales" AS "/", "t14".">", CASE WHEN "t6".">" THEN "t14"."*" / "t6"."store_sales" ELSE NULL END AS "CASE"
FROM (SELECT "t2"."ca_county", "t1"."d_year", SUM("t1"."ss_ext_sales_price") AS "store_sales", SUM("t1"."ss_ext_sales_price") > 0 AS ">"
FROM (SELECT "t"."ss_addr_sk", "t"."ss_ext_sales_price", "t0"."d_year", "t0"."d_qoy"
FROM (SELECT "ss_sold_date_sk", "ss_addr_sk", "ss_ext_sales_price"
FROM '/mnt/disks/tpcds/parquet/store_sales.parquet' AS store_sales) AS "t"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t0" ON "t"."ss_sold_date_sk" = "t0"."d_date_sk") AS "t1"
INNER JOIN (SELECT "ca_address_sk", "ca_county"
FROM '/mnt/disks/tpcds/parquet/customer_address.parquet' AS customer_address) AS "t2" ON "t1"."ss_addr_sk" = "t2"."ca_address_sk"
GROUP BY "t2"."ca_county", "t1"."d_qoy", "t1"."d_year"
HAVING "t1"."d_qoy" = 1 AND "t1"."d_year" = 2000) AS "t6"
INNER JOIN (SELECT "t10"."ca_county", SUM("t9"."ss_ext_sales_price") AS "store_sales", SUM("t9"."ss_ext_sales_price") * 1.0000 AS "*", SUM("t9"."ss_ext_sales_price") > 0 AS ">"
FROM (SELECT "t7"."ss_addr_sk", "t7"."ss_ext_sales_price", "t8"."d_year", "t8"."d_qoy"
FROM (SELECT "ss_sold_date_sk", "ss_addr_sk", "ss_ext_sales_price"
FROM '/mnt/disks/tpcds/parquet/store_sales.parquet' AS store_sales) AS "t7"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t8" ON "t7"."ss_sold_date_sk" = "t8"."d_date_sk") AS "t9"
INNER JOIN (SELECT "ca_address_sk", "ca_county"
FROM '/mnt/disks/tpcds/parquet/customer_address.parquet' AS customer_address) AS "t10" ON "t9"."ss_addr_sk" = "t10"."ca_address_sk"
GROUP BY "t10"."ca_county", "t9"."d_qoy", "t9"."d_year"
HAVING "t9"."d_qoy" = 2 AND "t9"."d_year" = 2000) AS "t14" ON "t6"."ca_county" = "t14"."ca_county") AS "t15"
INNER JOIN (SELECT "t19"."ca_county", SUM("t18"."ss_ext_sales_price") * 1.0000 AS "*"
FROM (SELECT "t16"."ss_addr_sk", "t16"."ss_ext_sales_price", "t17"."d_year", "t17"."d_qoy"
FROM (SELECT "ss_sold_date_sk", "ss_addr_sk", "ss_ext_sales_price"
FROM '/mnt/disks/tpcds/parquet/store_sales.parquet' AS store_sales) AS "t16"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t17" ON "t16"."ss_sold_date_sk" = "t17"."d_date_sk") AS "t18"
INNER JOIN (SELECT "ca_address_sk", "ca_county"
FROM '/mnt/disks/tpcds/parquet/customer_address.parquet' AS customer_address) AS "t19" ON "t18"."ss_addr_sk" = "t19"."ca_address_sk"
GROUP BY "t19"."ca_county", "t18"."d_qoy", "t18"."d_year"
HAVING "t18"."d_qoy" = 3 AND "t18"."d_year" = 2000) AS "t23" ON "t15"."ca_county0" = "t23"."ca_county") AS "t24"
INNER JOIN (SELECT "t28"."ca_county", SUM("t27"."ws_ext_sales_price") AS "web_sales", SUM("t27"."ws_ext_sales_price") > 0 AS ">"
FROM (SELECT "t25"."ws_bill_addr_sk", "t25"."ws_ext_sales_price", "t26"."d_year", "t26"."d_qoy"
FROM (SELECT "ws_sold_date_sk", "ws_bill_addr_sk", "ws_ext_sales_price"
FROM '/mnt/disks/tpcds/parquet/web_sales.parquet' AS web_sales) AS "t25"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t26" ON "t25"."ws_sold_date_sk" = "t26"."d_date_sk") AS "t27"
INNER JOIN (SELECT "ca_address_sk", "ca_county"
FROM '/mnt/disks/tpcds/parquet/customer_address.parquet' AS customer_address) AS "t28" ON "t27"."ws_bill_addr_sk" = "t28"."ca_address_sk"
GROUP BY "t28"."ca_county", "t27"."d_qoy", "t27"."d_year"
HAVING "t27"."d_qoy" = 1 AND "t27"."d_year" = 2000) AS "t32" ON "t24"."ca_county" = "t32"."ca_county") AS "t33"
INNER JOIN "duck_table_31_0" ON "t33"."ca_county2" = "duck_table_31_0"."ca_county" AND CASE WHEN "t33".">" THEN "duck_table_31_0"."*" / "t33"."web_sales" ELSE NULL END > "t33"."CASE8") AS "t35"
INNER JOIN (SELECT "t39"."ca_county", SUM("t38"."ws_ext_sales_price") * 1.0000 AS "*"
FROM (SELECT "t36"."ws_bill_addr_sk", "t36"."ws_ext_sales_price", "t37"."d_year", "t37"."d_qoy"
FROM (SELECT "ws_sold_date_sk", "ws_bill_addr_sk", "ws_ext_sales_price"
FROM '/mnt/disks/tpcds/parquet/web_sales.parquet' AS web_sales) AS "t36"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t37" ON "t36"."ws_sold_date_sk" = "t37"."d_date_sk") AS "t38"
INNER JOIN (SELECT "ca_address_sk", "ca_county"
FROM '/mnt/disks/tpcds/parquet/customer_address.parquet' AS customer_address) AS "t39" ON "t38"."ws_bill_addr_sk" = "t39"."ca_address_sk"
GROUP BY "t39"."ca_county", "t38"."d_qoy", "t38"."d_year"
HAVING "t38"."d_qoy" = 3 AND "t38"."d_year" = 2000) AS "t43" ON "t35"."ca_county2" = "t43"."ca_county" AND CASE WHEN "t35".">" THEN CAST("t43"."*" / "t35"."web_sales0" AS DECIMAL(19, 4)) ELSE NULL END > "t35"."CASE"
ORDER BY "t35"."ca_county";
