SELECT "t42"."ca_county", "t42"."d_year", "t42"."/" AS "web_q1_q2_increase", "t42"."/5" AS "store_q1_q2_increase", "t50"."*" / "t42"."web_sales0" AS "web_q2_q3_increase", "t42"."/6" AS "store_q2_q3_increase"
FROM (SELECT "t33"."ca_county", "t33"."d_year", "t33"."ca_county2", "t41"."web_sales" AS "web_sales0", "t41"."*" / "t33"."web_sales" AS "/", "t33"."/" AS "/5", "t33"."/5" AS "/6", "t41".">", "t33"."CASE"
FROM (SELECT "t24"."ca_county", "t24"."d_year", "t32"."ca_county" AS "ca_county2", "t32"."web_sales", "t24"."/", "t24"."/3" AS "/5", "t24"."CASE", "t32".">", "t24"."CASE5" AS "CASE8"
FROM (SELECT "t15"."ca_county", "t15"."d_year", "t15"."/", "t23"."*" / "t15"."store_sales0" AS "/3", CASE WHEN "t15".">" THEN "t23"."*" / "t15"."store_sales0" ELSE NULL END AS "CASE", "t15"."CASE" AS "CASE5"
FROM (SELECT "t6"."ca_county", "t6"."d_year", "t14"."ca_county" AS "ca_county0", "t14"."store_sales" AS "store_sales0", "t14"."*" / "t6"."store_sales" AS "/", "t14".">", CASE WHEN "t6".">" THEN "t14"."*" / "t6"."store_sales" ELSE NULL END AS "CASE"
FROM (SELECT "t5"."ca_county", "t5"."d_year", "t5"."store_sales", "t5"."store_sales" > 0 AS ">"
FROM (SELECT "t2"."ca_county", "t1"."d_qoy", "t1"."d_year", SUM("t1"."ss_ext_sales_price") AS "store_sales"
FROM (SELECT "t"."ss_addr_sk", "t"."ss_ext_sales_price", "t0"."d_year", "t0"."d_qoy"
FROM (SELECT "ss_sold_date_sk", "ss_addr_sk", "ss_ext_sales_price"
FROM store_sales) AS "t"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM date_dim) AS "t0" ON "t"."ss_sold_date_sk" = "t0"."d_date_sk") AS "t1"
INNER JOIN (SELECT "ca_address_sk", "ca_county"
FROM customer_address) AS "t2" ON "t1"."ss_addr_sk" = "t2"."ca_address_sk"
GROUP BY "t2"."ca_county", "t1"."d_qoy", "t1"."d_year"
HAVING "t1"."d_qoy" = 1 AND "t1"."d_year" = 2000) AS "t5") AS "t6"
INNER JOIN (SELECT "t13"."ca_county", "t13"."store_sales", "t13"."store_sales" * 1.0000 AS "*", "t13"."store_sales" > 0 AS ">"
FROM (SELECT "t10"."ca_county", "t9"."d_qoy", "t9"."d_year", SUM("t9"."ss_ext_sales_price") AS "store_sales"
FROM (SELECT "t7"."ss_addr_sk", "t7"."ss_ext_sales_price", "t8"."d_year", "t8"."d_qoy"
FROM (SELECT "ss_sold_date_sk", "ss_addr_sk", "ss_ext_sales_price"
FROM store_sales) AS "t7"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM date_dim) AS "t8" ON "t7"."ss_sold_date_sk" = "t8"."d_date_sk") AS "t9"
INNER JOIN (SELECT "ca_address_sk", "ca_county"
FROM customer_address) AS "t10" ON "t9"."ss_addr_sk" = "t10"."ca_address_sk"
GROUP BY "t10"."ca_county", "t9"."d_qoy", "t9"."d_year"
HAVING "t9"."d_qoy" = 2 AND "t9"."d_year" = 2000) AS "t13") AS "t14" ON "t6"."ca_county" = "t14"."ca_county") AS "t15"
INNER JOIN (SELECT "t22"."ca_county", "t22"."store_sales" * 1.0000 AS "*"
FROM (SELECT "t19"."ca_county", "t18"."d_qoy", "t18"."d_year", SUM("t18"."ss_ext_sales_price") AS "store_sales"
FROM (SELECT "t16"."ss_addr_sk", "t16"."ss_ext_sales_price", "t17"."d_year", "t17"."d_qoy"
FROM (SELECT "ss_sold_date_sk", "ss_addr_sk", "ss_ext_sales_price"
FROM store_sales) AS "t16"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM date_dim) AS "t17" ON "t16"."ss_sold_date_sk" = "t17"."d_date_sk") AS "t18"
INNER JOIN (SELECT "ca_address_sk", "ca_county"
FROM customer_address) AS "t19" ON "t18"."ss_addr_sk" = "t19"."ca_address_sk"
GROUP BY "t19"."ca_county", "t18"."d_qoy", "t18"."d_year"
HAVING "t18"."d_qoy" = 3 AND "t18"."d_year" = 2000) AS "t22") AS "t23" ON "t15"."ca_county0" = "t23"."ca_county") AS "t24"
INNER JOIN (SELECT "t31"."ca_county", "t31"."web_sales", "t31"."web_sales" > 0 AS ">"
FROM (SELECT "t28"."ca_county", "t27"."d_qoy", "t27"."d_year", SUM("t27"."ws_ext_sales_price") AS "web_sales"
FROM (SELECT "t25"."ws_bill_addr_sk", "t25"."ws_ext_sales_price", "t26"."d_year", "t26"."d_qoy"
FROM (SELECT "ws_sold_date_sk", "ws_bill_addr_sk", "ws_ext_sales_price"
FROM web_sales) AS "t25"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM date_dim) AS "t26" ON "t25"."ws_sold_date_sk" = "t26"."d_date_sk") AS "t27"
INNER JOIN (SELECT "ca_address_sk", "ca_county"
FROM customer_address) AS "t28" ON "t27"."ws_bill_addr_sk" = "t28"."ca_address_sk"
GROUP BY "t28"."ca_county", "t27"."d_qoy", "t27"."d_year"
HAVING "t27"."d_qoy" = 1 AND "t27"."d_year" = 2000) AS "t31") AS "t32" ON "t24"."ca_county" = "t32"."ca_county") AS "t33"
INNER JOIN (SELECT "t40"."ca_county", "t40"."web_sales", "t40"."web_sales" * 1.0000 AS "*", "t40"."web_sales" > 0 AS ">"
FROM (SELECT "t37"."ca_county", "t36"."d_qoy", "t36"."d_year", SUM("t36"."ws_ext_sales_price") AS "web_sales"
FROM (SELECT "t34"."ws_bill_addr_sk", "t34"."ws_ext_sales_price", "t35"."d_year", "t35"."d_qoy"
FROM (SELECT "ws_sold_date_sk", "ws_bill_addr_sk", "ws_ext_sales_price"
FROM web_sales) AS "t34"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM date_dim) AS "t35" ON "t34"."ws_sold_date_sk" = "t35"."d_date_sk") AS "t36"
INNER JOIN (SELECT "ca_address_sk", "ca_county"
FROM customer_address) AS "t37" ON "t36"."ws_bill_addr_sk" = "t37"."ca_address_sk"
GROUP BY "t37"."ca_county", "t36"."d_qoy", "t36"."d_year"
HAVING "t36"."d_qoy" = 2 AND "t36"."d_year" = 2000) AS "t40") AS "t41" ON "t33"."ca_county2" = "t41"."ca_county" AND CASE WHEN "t33".">" THEN "t41"."*" / "t33"."web_sales" ELSE NULL END > "t33"."CASE8") AS "t42"
INNER JOIN (SELECT "t49"."ca_county", "t49"."web_sales" * 1.0000 AS "*"
FROM (SELECT "t46"."ca_county", "t45"."d_qoy", "t45"."d_year", SUM("t45"."ws_ext_sales_price") AS "web_sales"
FROM (SELECT "t43"."ws_bill_addr_sk", "t43"."ws_ext_sales_price", "t44"."d_year", "t44"."d_qoy"
FROM (SELECT "ws_sold_date_sk", "ws_bill_addr_sk", "ws_ext_sales_price"
FROM web_sales) AS "t43"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM date_dim) AS "t44" ON "t43"."ws_sold_date_sk" = "t44"."d_date_sk") AS "t45"
INNER JOIN (SELECT "ca_address_sk", "ca_county"
FROM customer_address) AS "t46" ON "t45"."ws_bill_addr_sk" = "t46"."ca_address_sk"
GROUP BY "t46"."ca_county", "t45"."d_qoy", "t45"."d_year"
HAVING "t45"."d_qoy" = 3 AND "t45"."d_year" = 2000) AS "t49") AS "t50" ON "t42"."ca_county2" = "t50"."ca_county" AND CASE WHEN "t42".">" THEN CAST("t50"."*" / "t42"."web_sales0" AS DECIMAL(19, 4)) ELSE NULL END > "t42"."CASE"
ORDER BY "t42"."ca_county" IS NULL, "t42"."ca_county"
;
