SELECT "t21"."i_category", "t21"."i_brand", "t21"."s_store_name", "t21"."s_company_name", "t21"."d_year", "t21"."d_moy", "t21"."avg_monthly_sales", "t21"."sum_sales", "t21"."sum_sales0" AS "psum", "t32"."sum_sales" AS "nsum", "t21"."sum_sales" - "t21"."avg_monthly_sales"
FROM (SELECT "t9"."i_category", "t9"."i_brand", "t9"."s_store_name", "t9"."s_company_name", "t9"."d_year", "t9"."d_moy", "t9"."sum_sales", "t9"."avg_monthly_sales", "t9"."rn", "t20"."sum_sales" AS "sum_sales0"
FROM (SELECT "t7"."i_category", "t7"."i_brand", "t7"."s_store_name", "t7"."s_company_name", "t7"."d_year", "t7"."d_moy", "t7"."sum_sales", (SUM("t7"."sum_sales") OVER (PARTITION BY "t7"."i_category", "t7"."i_brand", "t7"."s_store_name", "t7"."s_company_name", "t7"."d_year" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)) / (COUNT("t7"."sum_sales") OVER (PARTITION BY "t7"."i_category", "t7"."i_brand", "t7"."s_store_name", "t7"."s_company_name", "t7"."d_year" RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)) AS "avg_monthly_sales", RANK() OVER (PARTITION BY "t7"."i_category", "t7"."i_brand", "t7"."s_store_name", "t7"."s_company_name" ORDER BY "t7"."d_year" IS NULL, "t7"."d_year", "t7"."d_moy" IS NULL, "t7"."d_moy") AS "rn"
FROM (SELECT "t4"."i_category", "t4"."i_brand", "t5"."s_store_name", "t5"."s_company_name", "t4"."d_year", "t4"."d_moy", SUM("t4"."ss_sales_price") AS "sum_sales"
FROM (SELECT "t1"."i_brand", "t1"."i_category", "t1"."ss_store_sk", "t1"."ss_sales_price", "t3"."d_year", "t3"."d_moy"
FROM (SELECT "t"."i_brand", "t"."i_category", "t0"."ss_sold_date_sk", "t0"."ss_store_sk", "t0"."ss_sales_price"
FROM (SELECT "i_item_sk", "i_brand", "i_category"
FROM item) AS "t"
INNER JOIN (SELECT "ss_sold_date_sk", "ss_item_sk", "ss_store_sk", "ss_sales_price"
FROM store_sales) AS "t0" ON "t"."i_item_sk" = "t0"."ss_item_sk") AS "t1"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_moy"
FROM date_dim
WHERE "d_year" = 1999 OR "d_year" = 1999 - 1 AND "d_moy" = 12 OR "d_year" = 1999 + 1 AND "d_moy" = 1) AS "t3" ON "t1"."ss_sold_date_sk" = "t3"."d_date_sk") AS "t4"
INNER JOIN (SELECT "s_store_sk", "s_store_name", "s_company_name"
FROM store) AS "t5" ON "t4"."ss_store_sk" = "t5"."s_store_sk"
GROUP BY "t4"."i_category", "t4"."i_brand", "t5"."s_store_name", "t5"."s_company_name", "t4"."d_year", "t4"."d_moy") AS "t7") AS "t9"
INNER JOIN (SELECT "t18"."i_category", "t18"."i_brand", "t18"."s_store_name", "t18"."s_company_name", "t18"."sum_sales", (RANK() OVER (PARTITION BY "t18"."i_category", "t18"."i_brand", "t18"."s_store_name", "t18"."s_company_name" ORDER BY "t18"."d_year" IS NULL, "t18"."d_year", "t18"."d_moy" IS NULL, "t18"."d_moy")) + 1 AS "+"
FROM (SELECT "t15"."i_category", "t15"."i_brand", "t16"."s_store_name", "t16"."s_company_name", "t15"."d_year", "t15"."d_moy", SUM("t15"."ss_sales_price") AS "sum_sales"
FROM (SELECT "t12"."i_brand", "t12"."i_category", "t12"."ss_store_sk", "t12"."ss_sales_price", "t14"."d_year", "t14"."d_moy"
FROM (SELECT "t10"."i_brand", "t10"."i_category", "t11"."ss_sold_date_sk", "t11"."ss_store_sk", "t11"."ss_sales_price"
FROM (SELECT "i_item_sk", "i_brand", "i_category"
FROM item) AS "t10"
INNER JOIN (SELECT "ss_sold_date_sk", "ss_item_sk", "ss_store_sk", "ss_sales_price"
FROM store_sales) AS "t11" ON "t10"."i_item_sk" = "t11"."ss_item_sk") AS "t12"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_moy"
FROM date_dim
WHERE "d_year" = 1999 OR "d_year" = 1999 - 1 AND "d_moy" = 12 OR "d_year" = 1999 + 1 AND "d_moy" = 1) AS "t14" ON "t12"."ss_sold_date_sk" = "t14"."d_date_sk") AS "t15"
INNER JOIN (SELECT "s_store_sk", "s_store_name", "s_company_name"
FROM store) AS "t16" ON "t15"."ss_store_sk" = "t16"."s_store_sk"
GROUP BY "t15"."i_category", "t15"."i_brand", "t16"."s_store_name", "t16"."s_company_name", "t15"."d_year", "t15"."d_moy") AS "t18") AS "t20" ON "t9"."i_category" = "t20"."i_category" AND "t9"."i_brand" = "t20"."i_brand" AND "t9"."s_store_name" = "t20"."s_store_name" AND "t9"."s_company_name" = "t20"."s_company_name" AND "t9"."rn" = "t20"."+") AS "t21"
INNER JOIN (SELECT "t30"."i_category", "t30"."i_brand", "t30"."s_store_name", "t30"."s_company_name", "t30"."sum_sales", (RANK() OVER (PARTITION BY "t30"."i_category", "t30"."i_brand", "t30"."s_store_name", "t30"."s_company_name" ORDER BY "t30"."d_year" IS NULL, "t30"."d_year", "t30"."d_moy" IS NULL, "t30"."d_moy")) - 1 AS "-"
FROM (SELECT "t27"."i_category", "t27"."i_brand", "t28"."s_store_name", "t28"."s_company_name", "t27"."d_year", "t27"."d_moy", SUM("t27"."ss_sales_price") AS "sum_sales"
FROM (SELECT "t24"."i_brand", "t24"."i_category", "t24"."ss_store_sk", "t24"."ss_sales_price", "t26"."d_year", "t26"."d_moy"
FROM (SELECT "t22"."i_brand", "t22"."i_category", "t23"."ss_sold_date_sk", "t23"."ss_store_sk", "t23"."ss_sales_price"
FROM (SELECT "i_item_sk", "i_brand", "i_category"
FROM item) AS "t22"
INNER JOIN (SELECT "ss_sold_date_sk", "ss_item_sk", "ss_store_sk", "ss_sales_price"
FROM store_sales) AS "t23" ON "t22"."i_item_sk" = "t23"."ss_item_sk") AS "t24"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_moy"
FROM date_dim
WHERE "d_year" = 1999 OR "d_year" = 1999 - 1 AND "d_moy" = 12 OR "d_year" = 1999 + 1 AND "d_moy" = 1) AS "t26" ON "t24"."ss_sold_date_sk" = "t26"."d_date_sk") AS "t27"
INNER JOIN (SELECT "s_store_sk", "s_store_name", "s_company_name"
FROM store) AS "t28" ON "t27"."ss_store_sk" = "t28"."s_store_sk"
GROUP BY "t27"."i_category", "t27"."i_brand", "t28"."s_store_name", "t28"."s_company_name", "t27"."d_year", "t27"."d_moy") AS "t30") AS "t32" ON "t21"."i_category" = "t32"."i_category" AND "t21"."i_brand" = "t32"."i_brand" AND "t21"."s_store_name" = "t32"."s_store_name" AND "t21"."s_company_name" = "t32"."s_company_name" AND "t21"."rn" = "t32"."-"
WHERE "t21"."d_year" = 1999 AND "t21"."avg_monthly_sales" > 0 AND CASE WHEN "t21"."avg_monthly_sales" > 0 THEN CAST(ABS("t21"."sum_sales" - "t21"."avg_monthly_sales") / "t21"."avg_monthly_sales" AS DECIMAL(19, 0)) ELSE NULL END > 0.1
ORDER BY "t21"."sum_sales" - "t21"."avg_monthly_sales" IS NULL, "t21"."sum_sales" - "t21"."avg_monthly_sales", "t21"."i_category" IS NULL, "t21"."i_category", "t21"."i_brand" IS NULL, "t21"."i_brand", "t21"."s_store_name" IS NULL, "t21"."s_store_name", "t21"."s_company_name" IS NULL, "t21"."s_company_name", "t21"."d_year" IS NULL, "t21"."d_year", "t21"."d_moy" IS NULL, "t21"."d_moy", "t21"."avg_monthly_sales" IS NULL, "t21"."avg_monthly_sales", "t21"."sum_sales" IS NULL, "t21"."sum_sales", "t21"."sum_sales0" IS NULL, "t21"."sum_sales0", "t32"."sum_sales" IS NULL, "t32"."sum_sales"
LIMIT 100
;
