SELECT "t10"."s_store_name1", "t10"."s_store_id1", "t10"."d_week_seq1", "t10"."sun_sales1" / "t22"."sun_sales2", "t10"."mon_sales1" / "t22"."mon_sales2", "t10"."tue_sales1" / "t22"."tue_sales2", "t10"."wed_sales1" / "t22"."wed_sales2", "t10"."thu_sales1" / "t22"."thu_sales2", "t10"."fri_sales1" / "t22"."fri_sales2", "t10"."sat_sales1" / "t22"."sat_sales2"
FROM (SELECT "t5"."s_store_name" AS "s_store_name1", "t5"."d_week_seq" AS "d_week_seq1", "t5"."s_store_id" AS "s_store_id1", "t5"."sun_sales" AS "sun_sales1", "t5"."mon_sales" AS "mon_sales1", "t5"."tue_sales" AS "tue_sales1", "t5"."wed_sales" AS "wed_sales1", "t5"."thu_sales" AS "thu_sales1", "t5"."fri_sales" AS "fri_sales1", "t5"."sat_sales" AS "sat_sales1"
FROM (SELECT "t3"."d_week_seq", "t3"."sun_sales", "t3"."mon_sales", "t3"."tue_sales", "t3"."wed_sales", "t3"."thu_sales", "t3"."fri_sales", "t3"."sat_sales", "t4"."s_store_id", "t4"."s_store_name"
FROM (SELECT "t0"."d_week_seq", "t"."ss_store_sk", SUM("t"."ss_sales_price") FILTER (WHERE "t0"."=") AS "sun_sales", SUM("t"."ss_sales_price") FILTER (WHERE "t0"."=3") AS "mon_sales", SUM("t"."ss_sales_price") FILTER (WHERE "t0"."=4") AS "tue_sales", SUM("t"."ss_sales_price") FILTER (WHERE "t0"."=5") AS "wed_sales", SUM("t"."ss_sales_price") FILTER (WHERE "t0"."=6") AS "thu_sales", SUM("t"."ss_sales_price") FILTER (WHERE "t0"."=7") AS "fri_sales", SUM("t"."ss_sales_price") FILTER (WHERE "t0"."=8") AS "sat_sales"
FROM (SELECT "ss_sold_date_sk", "ss_store_sk", "ss_sales_price"
FROM store_sales) AS "t"
INNER JOIN (SELECT "d_date_sk", "d_week_seq", "d_day_name" = 'Sunday' AS "=", "d_day_name" = 'Monday' AS "=3", "d_day_name" = 'Tuesday' AS "=4", "d_day_name" = 'Wednesday' AS "=5", "d_day_name" = 'Thursday' AS "=6", "d_day_name" = 'Friday' AS "=7", "d_day_name" = 'Saturday' AS "=8"
FROM date_dim) AS "t0" ON "t"."ss_sold_date_sk" = "t0"."d_date_sk"
GROUP BY "t0"."d_week_seq", "t"."ss_store_sk") AS "t3"
INNER JOIN (SELECT "s_store_sk", "s_store_id", "s_store_name"
FROM store) AS "t4" ON "t3"."ss_store_sk" = "t4"."s_store_sk") AS "t5"
INNER JOIN (SELECT "d_week_seq"
FROM date_dim
WHERE "d_month_seq" >= 1212 AND "d_month_seq" <= 1212 + 11) AS "t8" ON "t5"."d_week_seq" = "t8"."d_week_seq") AS "t10"
INNER JOIN (SELECT "t17"."s_store_id" AS "s_store_id2", "t17"."sun_sales" AS "sun_sales2", "t17"."mon_sales" AS "mon_sales2", "t17"."tue_sales" AS "tue_sales2", "t17"."wed_sales" AS "wed_sales2", "t17"."thu_sales" AS "thu_sales2", "t17"."fri_sales" AS "fri_sales2", "t17"."sat_sales" AS "sat_sales2", "t17"."d_week_seq" - 52 AS "-"
FROM (SELECT "t15"."d_week_seq", "t15"."sun_sales", "t15"."mon_sales", "t15"."tue_sales", "t15"."wed_sales", "t15"."thu_sales", "t15"."fri_sales", "t15"."sat_sales", "t16"."s_store_id", "t16"."s_store_name"
FROM (SELECT "t12"."d_week_seq", "t11"."ss_store_sk", SUM("t11"."ss_sales_price") FILTER (WHERE "t12"."=") AS "sun_sales", SUM("t11"."ss_sales_price") FILTER (WHERE "t12"."=3") AS "mon_sales", SUM("t11"."ss_sales_price") FILTER (WHERE "t12"."=4") AS "tue_sales", SUM("t11"."ss_sales_price") FILTER (WHERE "t12"."=5") AS "wed_sales", SUM("t11"."ss_sales_price") FILTER (WHERE "t12"."=6") AS "thu_sales", SUM("t11"."ss_sales_price") FILTER (WHERE "t12"."=7") AS "fri_sales", SUM("t11"."ss_sales_price") FILTER (WHERE "t12"."=8") AS "sat_sales"
FROM (SELECT "ss_sold_date_sk", "ss_store_sk", "ss_sales_price"
FROM store_sales) AS "t11"
INNER JOIN (SELECT "d_date_sk", "d_week_seq", "d_day_name" = 'Sunday' AS "=", "d_day_name" = 'Monday' AS "=3", "d_day_name" = 'Tuesday' AS "=4", "d_day_name" = 'Wednesday' AS "=5", "d_day_name" = 'Thursday' AS "=6", "d_day_name" = 'Friday' AS "=7", "d_day_name" = 'Saturday' AS "=8"
FROM date_dim) AS "t12" ON "t11"."ss_sold_date_sk" = "t12"."d_date_sk"
GROUP BY "t12"."d_week_seq", "t11"."ss_store_sk") AS "t15"
INNER JOIN (SELECT "s_store_sk", "s_store_id", "s_store_name"
FROM store) AS "t16" ON "t15"."ss_store_sk" = "t16"."s_store_sk") AS "t17"
INNER JOIN (SELECT "d_week_seq"
FROM date_dim
WHERE "d_month_seq" >= 1212 + 12 AND "d_month_seq" <= 1212 + 23) AS "t20" ON "t17"."d_week_seq" = "t20"."d_week_seq") AS "t22" ON "t10"."s_store_id1" = "t22"."s_store_id2" AND "t10"."d_week_seq1" = "t22"."-"
ORDER BY "t10"."s_store_name1", "t10"."s_store_id1", "t10"."d_week_seq1"
LIMIT 100
;
