SELECT "w_warehouse_name", "w_warehouse_sq_ft", "w_city", "w_county", "w_state", "w_country", "ship_carriers", "year_", SUM("jan_sales") AS "jan_sales", SUM("feb_sales") AS "feb_sales", SUM("mar_sales") AS "mar_sales", SUM("apr_sales") AS "apr_sales", SUM("may_sales") AS "may_sales", SUM("jun_sales") AS "jun_sales", SUM("jul_sales") AS "jul_sales", SUM("aug_sales") AS "aug_sales", SUM("sep_sales") AS "sep_sales", SUM("oct_sales") AS "oct_sales", SUM("nov_sales") AS "nov_sales", SUM("dec_sales") AS "dec_sales", SUM("jan_sales" / "w_warehouse_sq_ft") AS "jan_sales_per_sq_foot", SUM("feb_sales" / "w_warehouse_sq_ft") AS "feb_sales_per_sq_foot", SUM("mar_sales" / "w_warehouse_sq_ft") AS "mar_sales_per_sq_foot", SUM("apr_sales" / "w_warehouse_sq_ft") AS "apr_sales_per_sq_foot", SUM("may_sales" / "w_warehouse_sq_ft") AS "may_sales_per_sq_foot", SUM("jun_sales" / "w_warehouse_sq_ft") AS "jun_sales_per_sq_foot", SUM("jul_sales" / "w_warehouse_sq_ft") AS "jul_sales_per_sq_foot", SUM("aug_sales" / "w_warehouse_sq_ft") AS "aug_sales_per_sq_foot", SUM("sep_sales" / "w_warehouse_sq_ft") AS "sep_sales_per_sq_foot", SUM("oct_sales" / "w_warehouse_sq_ft") AS "oct_sales_per_sq_foot", SUM("nov_sales" / "w_warehouse_sq_ft") AS "nov_sales_per_sq_foot", SUM("dec_sales" / "w_warehouse_sq_ft") AS "dec_sales_per_sq_foot", SUM("jan_net") AS "jan_net", SUM("feb_net") AS "feb_net", SUM("mar_net") AS "mar_net", SUM("apr_net") AS "apr_net", SUM("may_net") AS "may_net", SUM("jun_net") AS "jun_net", SUM("jul_net") AS "jul_net", SUM("aug_net") AS "aug_net", SUM("sep_net") AS "sep_net", SUM("oct_net") AS "oct_net", SUM("nov_net") AS "nov_net", SUM("dec_net") AS "dec_net"
FROM (SELECT "t9"."w_warehouse_name", "t9"."w_warehouse_sq_ft", "t9"."w_city", "t9"."w_county", "t9"."w_state", "t9"."w_country", 'DHL,BARIAN' AS "ship_carriers", "t9"."d_year" AS "year_", SUM("t9"."CASE") AS "jan_sales", SUM("t9"."CASE9") AS "feb_sales", SUM("t9"."CASE10") AS "mar_sales", SUM("t9"."CASE11") AS "apr_sales", SUM("t9"."CASE12") AS "may_sales", SUM("t9"."CASE13") AS "jun_sales", SUM("t9"."CASE14") AS "jul_sales", SUM("t9"."CASE15") AS "aug_sales", SUM("t9"."CASE16") AS "sep_sales", SUM("t9"."CASE17") AS "oct_sales", SUM("t9"."CASE18") AS "nov_sales", SUM("t9"."CASE19") AS "dec_sales", SUM("t9"."CASE20") AS "jan_net", SUM("t9"."CASE21") AS "feb_net", SUM("t9"."CASE22") AS "mar_net", SUM("t9"."CASE23") AS "apr_net", SUM("t9"."CASE24") AS "may_net", SUM("t9"."CASE25") AS "jun_net", SUM("t9"."CASE26") AS "jul_net", SUM("t9"."CASE27") AS "aug_net", SUM("t9"."CASE28") AS "sep_net", SUM("t9"."CASE29") AS "oct_net", SUM("t9"."CASE30") AS "nov_net", SUM("t9"."CASE31") AS "dec_net"
FROM (SELECT "t5"."ws_ship_mode_sk", "t5"."w_warehouse_name", "t5"."w_warehouse_sq_ft", "t5"."w_city", "t5"."w_county", "t5"."w_state", "t5"."w_country", "t5"."d_year", "t5"."CASE", "t5"."CASE10" AS "CASE9", "t5"."CASE11" AS "CASE10", "t5"."CASE12" AS "CASE11", "t5"."CASE13" AS "CASE12", "t5"."CASE14" AS "CASE13", "t5"."CASE15" AS "CASE14", "t5"."CASE16" AS "CASE15", "t5"."CASE17" AS "CASE16", "t5"."CASE18" AS "CASE17", "t5"."CASE19" AS "CASE18", "t5"."CASE20" AS "CASE19", "t5"."CASE21" AS "CASE20", "t5"."CASE22" AS "CASE21", "t5"."CASE23" AS "CASE22", "t5"."CASE24" AS "CASE23", "t5"."CASE25" AS "CASE24", "t5"."CASE26" AS "CASE25", "t5"."CASE27" AS "CASE26", "t5"."CASE28" AS "CASE27", "t5"."CASE29" AS "CASE28", "t5"."CASE30" AS "CASE29", "t5"."CASE31" AS "CASE30", "t5"."CASE32" AS "CASE31"
FROM (SELECT "t1"."ws_sold_time_sk", "t1"."ws_ship_mode_sk", "t1"."w_warehouse_name", "t1"."w_warehouse_sq_ft", "t1"."w_city", "t1"."w_county", "t1"."w_state", "t1"."w_country", "t4"."d_year", CASE WHEN "t4"."=" THEN "t1"."*" ELSE 0 END AS "CASE", CASE WHEN "t4"."=3" THEN "t1"."*" ELSE 0 END AS "CASE10", CASE WHEN "t4"."=4" THEN "t1"."*" ELSE 0 END AS "CASE11", CASE WHEN "t4"."=5" THEN "t1"."*" ELSE 0 END AS "CASE12", CASE WHEN "t4"."=6" THEN "t1"."*" ELSE 0 END AS "CASE13", CASE WHEN "t4"."=7" THEN "t1"."*" ELSE 0 END AS "CASE14", CASE WHEN "t4"."=8" THEN "t1"."*" ELSE 0 END AS "CASE15", CASE WHEN "t4"."=9" THEN "t1"."*" ELSE 0 END AS "CASE16", CASE WHEN "t4"."=10" THEN "t1"."*" ELSE 0 END AS "CASE17", CASE WHEN "t4"."=11" THEN "t1"."*" ELSE 0 END AS "CASE18", CASE WHEN "t4"."=12" THEN "t1"."*" ELSE 0 END AS "CASE19", CASE WHEN "t4"."=13" THEN "t1"."*" ELSE 0 END AS "CASE20", CASE WHEN "t4"."=" THEN "t1"."*10" ELSE 0 END AS "CASE21", CASE WHEN "t4"."=3" THEN "t1"."*10" ELSE 0 END AS "CASE22", CASE WHEN "t4"."=4" THEN "t1"."*10" ELSE 0 END AS "CASE23", CASE WHEN "t4"."=5" THEN "t1"."*10" ELSE 0 END AS "CASE24", CASE WHEN "t4"."=6" THEN "t1"."*10" ELSE 0 END AS "CASE25", CASE WHEN "t4"."=7" THEN "t1"."*10" ELSE 0 END AS "CASE26", CASE WHEN "t4"."=8" THEN "t1"."*10" ELSE 0 END AS "CASE27", CASE WHEN "t4"."=9" THEN "t1"."*10" ELSE 0 END AS "CASE28", CASE WHEN "t4"."=10" THEN "t1"."*10" ELSE 0 END AS "CASE29", CASE WHEN "t4"."=11" THEN "t1"."*10" ELSE 0 END AS "CASE30", CASE WHEN "t4"."=12" THEN "t1"."*10" ELSE 0 END AS "CASE31", CASE WHEN "t4"."=13" THEN "t1"."*10" ELSE 0 END AS "CASE32"
FROM (SELECT "t"."ws_sold_date_sk", "t"."ws_sold_time_sk", "t"."ws_ship_mode_sk", "t0"."w_warehouse_name", "t0"."w_warehouse_sq_ft", "t0"."w_city", "t0"."w_county", "t0"."w_state", "t0"."w_country", "t"."*" AS "*", "t"."*5" AS "*10"
FROM (SELECT "ws_sold_date_sk", "ws_sold_time_sk", "ws_ship_mode_sk", "ws_warehouse_sk", "ws_ext_sales_price" * "ws_quantity" AS "*", "ws_net_paid" * "ws_quantity" AS "*5"
FROM web_sales) AS "t"
INNER JOIN (SELECT "w_warehouse_sk", "w_warehouse_name", "w_warehouse_sq_ft", "w_city", "w_county", "w_state", "w_country"
FROM warehouse) AS "t0" ON "t"."ws_warehouse_sk" = "t0"."w_warehouse_sk") AS "t1"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_moy" = 1 AS "=", "d_moy" = 2 AS "=3", "d_moy" = 3 AS "=4", "d_moy" = 4 AS "=5", "d_moy" = 5 AS "=6", "d_moy" = 6 AS "=7", "d_moy" = 7 AS "=8", "d_moy" = 8 AS "=9", "d_moy" = 9 AS "=10", "d_moy" = 10 AS "=11", "d_moy" = 11 AS "=12", "d_moy" = 12 AS "=13"
FROM date_dim
WHERE "d_year" = 2001) AS "t4" ON "t1"."ws_sold_date_sk" = "t4"."d_date_sk") AS "t5"
INNER JOIN (SELECT "t_time_sk"
FROM time_dim
WHERE "t_time" >= 30838 AND "t_time" <= 30838 + 28800) AS "t8" ON "t5"."ws_sold_time_sk" = "t8"."t_time_sk") AS "t9"
INNER JOIN (SELECT "sm_ship_mode_sk"
FROM ship_mode
WHERE "sm_carrier" IN ('BARIAN', 'DHL')) AS "t12" ON "t9"."ws_ship_mode_sk" = "t12"."sm_ship_mode_sk"
GROUP BY "t9"."w_warehouse_name", "t9"."w_warehouse_sq_ft", "t9"."w_city", "t9"."w_county", "t9"."w_state", "t9"."w_country", "t9"."d_year"
UNION ALL
SELECT "t26"."w_warehouse_name", "t26"."w_warehouse_sq_ft", "t26"."w_city", "t26"."w_county", "t26"."w_state", "t26"."w_country", 'DHL,BARIAN' AS "ship_carriers", "t26"."d_year" AS "year_", SUM("t26"."CASE") AS "jan_sales", SUM("t26"."CASE9") AS "feb_sales", SUM("t26"."CASE10") AS "mar_sales", SUM("t26"."CASE11") AS "apr_sales", SUM("t26"."CASE12") AS "may_sales", SUM("t26"."CASE13") AS "jun_sales", SUM("t26"."CASE14") AS "jul_sales", SUM("t26"."CASE15") AS "aug_sales", SUM("t26"."CASE16") AS "sep_sales", SUM("t26"."CASE17") AS "oct_sales", SUM("t26"."CASE18") AS "nov_sales", SUM("t26"."CASE19") AS "dec_sales", SUM("t26"."CASE20") AS "jan_net", SUM("t26"."CASE21") AS "feb_net", SUM("t26"."CASE22") AS "mar_net", SUM("t26"."CASE23") AS "apr_net", SUM("t26"."CASE24") AS "may_net", SUM("t26"."CASE25") AS "jun_net", SUM("t26"."CASE26") AS "jul_net", SUM("t26"."CASE27") AS "aug_net", SUM("t26"."CASE28") AS "sep_net", SUM("t26"."CASE29") AS "oct_net", SUM("t26"."CASE30") AS "nov_net", SUM("t26"."CASE31") AS "dec_net"
FROM (SELECT "t22"."cs_ship_mode_sk", "t22"."w_warehouse_name", "t22"."w_warehouse_sq_ft", "t22"."w_city", "t22"."w_county", "t22"."w_state", "t22"."w_country", "t22"."d_year", "t22"."CASE", "t22"."CASE10" AS "CASE9", "t22"."CASE11" AS "CASE10", "t22"."CASE12" AS "CASE11", "t22"."CASE13" AS "CASE12", "t22"."CASE14" AS "CASE13", "t22"."CASE15" AS "CASE14", "t22"."CASE16" AS "CASE15", "t22"."CASE17" AS "CASE16", "t22"."CASE18" AS "CASE17", "t22"."CASE19" AS "CASE18", "t22"."CASE20" AS "CASE19", "t22"."CASE21" AS "CASE20", "t22"."CASE22" AS "CASE21", "t22"."CASE23" AS "CASE22", "t22"."CASE24" AS "CASE23", "t22"."CASE25" AS "CASE24", "t22"."CASE26" AS "CASE25", "t22"."CASE27" AS "CASE26", "t22"."CASE28" AS "CASE27", "t22"."CASE29" AS "CASE28", "t22"."CASE30" AS "CASE29", "t22"."CASE31" AS "CASE30", "t22"."CASE32" AS "CASE31"
FROM (SELECT "t18"."cs_sold_time_sk", "t18"."cs_ship_mode_sk", "t18"."w_warehouse_name", "t18"."w_warehouse_sq_ft", "t18"."w_city", "t18"."w_county", "t18"."w_state", "t18"."w_country", "t21"."d_year", CASE WHEN "t21"."=" THEN "t18"."*" ELSE 0 END AS "CASE", CASE WHEN "t21"."=3" THEN "t18"."*" ELSE 0 END AS "CASE10", CASE WHEN "t21"."=4" THEN "t18"."*" ELSE 0 END AS "CASE11", CASE WHEN "t21"."=5" THEN "t18"."*" ELSE 0 END AS "CASE12", CASE WHEN "t21"."=6" THEN "t18"."*" ELSE 0 END AS "CASE13", CASE WHEN "t21"."=7" THEN "t18"."*" ELSE 0 END AS "CASE14", CASE WHEN "t21"."=8" THEN "t18"."*" ELSE 0 END AS "CASE15", CASE WHEN "t21"."=9" THEN "t18"."*" ELSE 0 END AS "CASE16", CASE WHEN "t21"."=10" THEN "t18"."*" ELSE 0 END AS "CASE17", CASE WHEN "t21"."=11" THEN "t18"."*" ELSE 0 END AS "CASE18", CASE WHEN "t21"."=12" THEN "t18"."*" ELSE 0 END AS "CASE19", CASE WHEN "t21"."=13" THEN "t18"."*" ELSE 0 END AS "CASE20", CASE WHEN "t21"."=" THEN "t18"."*10" ELSE 0 END AS "CASE21", CASE WHEN "t21"."=3" THEN "t18"."*10" ELSE 0 END AS "CASE22", CASE WHEN "t21"."=4" THEN "t18"."*10" ELSE 0 END AS "CASE23", CASE WHEN "t21"."=5" THEN "t18"."*10" ELSE 0 END AS "CASE24", CASE WHEN "t21"."=6" THEN "t18"."*10" ELSE 0 END AS "CASE25", CASE WHEN "t21"."=7" THEN "t18"."*10" ELSE 0 END AS "CASE26", CASE WHEN "t21"."=8" THEN "t18"."*10" ELSE 0 END AS "CASE27", CASE WHEN "t21"."=9" THEN "t18"."*10" ELSE 0 END AS "CASE28", CASE WHEN "t21"."=10" THEN "t18"."*10" ELSE 0 END AS "CASE29", CASE WHEN "t21"."=11" THEN "t18"."*10" ELSE 0 END AS "CASE30", CASE WHEN "t21"."=12" THEN "t18"."*10" ELSE 0 END AS "CASE31", CASE WHEN "t21"."=13" THEN "t18"."*10" ELSE 0 END AS "CASE32"
FROM (SELECT "t16"."cs_sold_date_sk", "t16"."cs_sold_time_sk", "t16"."cs_ship_mode_sk", "t17"."w_warehouse_name", "t17"."w_warehouse_sq_ft", "t17"."w_city", "t17"."w_county", "t17"."w_state", "t17"."w_country", "t16"."*" AS "*", "t16"."*5" AS "*10"
FROM (SELECT "cs_sold_date_sk", "cs_sold_time_sk", "cs_ship_mode_sk", "cs_warehouse_sk", "cs_sales_price" * "cs_quantity" AS "*", "cs_net_paid_inc_tax" * "cs_quantity" AS "*5"
FROM catalog_sales) AS "t16"
INNER JOIN (SELECT "w_warehouse_sk", "w_warehouse_name", "w_warehouse_sq_ft", "w_city", "w_county", "w_state", "w_country"
FROM warehouse) AS "t17" ON "t16"."cs_warehouse_sk" = "t17"."w_warehouse_sk") AS "t18"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_moy" = 1 AS "=", "d_moy" = 2 AS "=3", "d_moy" = 3 AS "=4", "d_moy" = 4 AS "=5", "d_moy" = 5 AS "=6", "d_moy" = 6 AS "=7", "d_moy" = 7 AS "=8", "d_moy" = 8 AS "=9", "d_moy" = 9 AS "=10", "d_moy" = 10 AS "=11", "d_moy" = 11 AS "=12", "d_moy" = 12 AS "=13"
FROM date_dim
WHERE "d_year" = 2001) AS "t21" ON "t18"."cs_sold_date_sk" = "t21"."d_date_sk") AS "t22"
INNER JOIN (SELECT "t_time_sk"
FROM time_dim
WHERE "t_time" >= 30838 AND "t_time" <= 30838 + 28800) AS "t25" ON "t22"."cs_sold_time_sk" = "t25"."t_time_sk") AS "t26"
INNER JOIN (SELECT "sm_ship_mode_sk"
FROM ship_mode
WHERE "sm_carrier" IN ('BARIAN', 'DHL')) AS "t29" ON "t26"."cs_ship_mode_sk" = "t29"."sm_ship_mode_sk"
GROUP BY "t26"."w_warehouse_name", "t26"."w_warehouse_sq_ft", "t26"."w_city", "t26"."w_county", "t26"."w_state", "t26"."w_country", "t26"."d_year") AS "t33"
GROUP BY "w_warehouse_name", "w_warehouse_sq_ft", "w_city", "w_county", "w_state", "w_country", "ship_carriers", "year_"
ORDER BY "w_warehouse_name"
LIMIT 100
;
