SELECT "channel", "col_name", "d_year", "d_qoy", "i_category", COUNT(*) AS "sales_cnt", SUM("ext_sales_price") AS "sales_amt"
FROM (SELECT *
FROM (SELECT 'store' AS "channel", 'ss_store_sk' AS "col_name", "t1"."d_year", "t1"."d_qoy", "t0"."i_category", "t0"."ss_ext_sales_price" AS "ext_sales_price"
FROM (SELECT "ss_sold_date_sk", "ss_ext_sales_price", "i_category"
FROM (SELECT NULL AS "ss_sold_date_sk", NULL AS "ss_sold_time_sk", NULL AS "ss_item_sk", NULL AS "ss_customer_sk", NULL AS "ss_cdemo_sk", NULL AS "ss_hdemo_sk", NULL AS "ss_addr_sk", NULL AS "ss_store_sk", NULL AS "ss_promo_sk", NULL AS "ss_ticket_number", NULL AS "ss_quantity", NULL AS "ss_wholesale_cost", NULL AS "ss_list_price", NULL AS "ss_sales_price", NULL AS "ss_ext_discount_amt", NULL AS "ss_ext_sales_price", NULL AS "ss_ext_wholesale_cost", NULL AS "ss_ext_list_price", NULL AS "ss_ext_tax", NULL AS "ss_coupon_amt", NULL AS "ss_net_paid", NULL AS "ss_net_paid_inc_tax", NULL AS "ss_net_profit", NULL AS "i_item_sk", NULL AS "i_item_id", NULL AS "i_rec_start_date", NULL AS "i_rec_end_date", NULL AS "i_item_desc", NULL AS "i_current_price", NULL AS "i_wholesale_cost", NULL AS "i_brand_id", NULL AS "i_brand", NULL AS "i_class_id", NULL AS "i_class", NULL AS "i_category_id", NULL AS "i_category", NULL AS "i_manufact_id", NULL AS "i_manufact", NULL AS "i_size", NULL AS "i_formulation", NULL AS "i_color", NULL AS "i_units", NULL AS "i_container", NULL AS "i_manager_id", NULL AS "i_product_name") AS "t"
WHERE 1 = 0) AS "t0"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM date_dim) AS "t1" ON "t0"."ss_sold_date_sk" = "t1"."d_date_sk"
UNION ALL
SELECT 'web' AS "channel", 'ws_ship_customer_sk' AS "col_name", "t5"."d_year", "t5"."d_qoy", "t4"."i_category", "t4"."ws_ext_sales_price" AS "ext_sales_price"
FROM (SELECT "ws_sold_date_sk", "ws_ext_sales_price", "i_category"
FROM (SELECT NULL AS "ws_sold_date_sk", NULL AS "ws_sold_time_sk", NULL AS "ws_ship_date_sk", NULL AS "ws_item_sk", NULL AS "ws_bill_customer_sk", NULL AS "ws_bill_cdemo_sk", NULL AS "ws_bill_hdemo_sk", NULL AS "ws_bill_addr_sk", NULL AS "ws_ship_customer_sk", NULL AS "ws_ship_cdemo_sk", NULL AS "ws_ship_hdemo_sk", NULL AS "ws_ship_addr_sk", NULL AS "ws_web_page_sk", NULL AS "ws_web_site_sk", NULL AS "ws_ship_mode_sk", NULL AS "ws_warehouse_sk", NULL AS "ws_promo_sk", NULL AS "ws_order_number", NULL AS "ws_quantity", NULL AS "ws_wholesale_cost", NULL AS "ws_list_price", NULL AS "ws_sales_price", NULL AS "ws_ext_discount_amt", NULL AS "ws_ext_sales_price", NULL AS "ws_ext_wholesale_cost", NULL AS "ws_ext_list_price", NULL AS "ws_ext_tax", NULL AS "ws_coupon_amt", NULL AS "ws_ext_ship_cost", NULL AS "ws_net_paid", NULL AS "ws_net_paid_inc_tax", NULL AS "ws_net_paid_inc_ship", NULL AS "ws_net_paid_inc_ship_tax", NULL AS "ws_net_profit", NULL AS "i_item_sk", NULL AS "i_item_id", NULL AS "i_rec_start_date", NULL AS "i_rec_end_date", NULL AS "i_item_desc", NULL AS "i_current_price", NULL AS "i_wholesale_cost", NULL AS "i_brand_id", NULL AS "i_brand", NULL AS "i_class_id", NULL AS "i_class", NULL AS "i_category_id", NULL AS "i_category", NULL AS "i_manufact_id", NULL AS "i_manufact", NULL AS "i_size", NULL AS "i_formulation", NULL AS "i_color", NULL AS "i_units", NULL AS "i_container", NULL AS "i_manager_id", NULL AS "i_product_name") AS "t"
WHERE 1 = 0) AS "t4"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM date_dim) AS "t5" ON "t4"."ws_sold_date_sk" = "t5"."d_date_sk") AS "t"
UNION ALL
SELECT 'catalog' AS "channel", 'cs_ship_addr_sk' AS "col_name", "t10"."d_year", "t10"."d_qoy", "t9"."i_category", "t9"."cs_ext_sales_price" AS "ext_sales_price"
FROM (SELECT "cs_sold_date_sk", "cs_ext_sales_price", "i_category"
FROM (SELECT NULL AS "cs_sold_date_sk", NULL AS "cs_sold_time_sk", NULL AS "cs_ship_date_sk", NULL AS "cs_bill_customer_sk", NULL AS "cs_bill_cdemo_sk", NULL AS "cs_bill_hdemo_sk", NULL AS "cs_bill_addr_sk", NULL AS "cs_ship_customer_sk", NULL AS "cs_ship_cdemo_sk", NULL AS "cs_ship_hdemo_sk", NULL AS "cs_ship_addr_sk", NULL AS "cs_call_center_sk", NULL AS "cs_catalog_page_sk", NULL AS "cs_ship_mode_sk", NULL AS "cs_warehouse_sk", NULL AS "cs_item_sk", NULL AS "cs_promo_sk", NULL AS "cs_order_number", NULL AS "cs_quantity", NULL AS "cs_wholesale_cost", NULL AS "cs_list_price", NULL AS "cs_sales_price", NULL AS "cs_ext_discount_amt", NULL AS "cs_ext_sales_price", NULL AS "cs_ext_wholesale_cost", NULL AS "cs_ext_list_price", NULL AS "cs_ext_tax", NULL AS "cs_coupon_amt", NULL AS "cs_ext_ship_cost", NULL AS "cs_net_paid", NULL AS "cs_net_paid_inc_tax", NULL AS "cs_net_paid_inc_ship", NULL AS "cs_net_paid_inc_ship_tax", NULL AS "cs_net_profit", NULL AS "i_item_sk", NULL AS "i_item_id", NULL AS "i_rec_start_date", NULL AS "i_rec_end_date", NULL AS "i_item_desc", NULL AS "i_current_price", NULL AS "i_wholesale_cost", NULL AS "i_brand_id", NULL AS "i_brand", NULL AS "i_class_id", NULL AS "i_class", NULL AS "i_category_id", NULL AS "i_category", NULL AS "i_manufact_id", NULL AS "i_manufact", NULL AS "i_size", NULL AS "i_formulation", NULL AS "i_color", NULL AS "i_units", NULL AS "i_container", NULL AS "i_manager_id", NULL AS "i_product_name") AS "t"
WHERE 1 = 0) AS "t9"
INNER JOIN (SELECT "d_date_sk", "d_year", "d_qoy"
FROM date_dim) AS "t10" ON "t9"."cs_sold_date_sk" = "t10"."d_date_sk") AS "t12"
GROUP BY "channel", "col_name", "d_year", "d_qoy", "i_category"
ORDER BY "channel", "col_name", "d_year", "d_qoy", "i_category"
LIMIT 100
;
