CREATE TABLE duck_table_04_0 AS SELECT *
FROM (SELECT "t1"."c_customer_id" AS "customer_id", "t1"."c_first_name" AS "customer_first_name", "t1"."c_last_name" AS "customer_last_name", "t1"."c_preferred_cust_flag" AS "customer_preferred_cust_flag", "t1"."c_birth_country" AS "customer_birth_country", "t1"."c_login" AS "customer_login", "t1"."c_email_address" AS "customer_email_address", "t2"."d_year" AS "dyear", SUM("t1"."/") AS "year_total", 's' AS "sale_type"
FROM (SELECT "t"."c_customer_id", "t"."c_first_name", "t"."c_last_name", "t"."c_preferred_cust_flag", "t"."c_birth_country", "t"."c_login", "t"."c_email_address", "t0"."ss_sold_date_sk", "t0"."/"
FROM (SELECT "c_customer_sk", "c_customer_id", "c_first_name", "c_last_name", "c_preferred_cust_flag", "c_birth_country", "c_login", "c_email_address"
FROM '/mnt/disks/tpcds/parquet/customer.parquet' AS customer) AS "t"
INNER JOIN (SELECT "ss_sold_date_sk", "ss_customer_sk", ("ss_ext_list_price" - "ss_ext_wholesale_cost" - "ss_ext_discount_amt" + "ss_ext_sales_price") / 2 AS "/"
FROM '/mnt/disks/tpcds/parquet/store_sales.parquet' AS store_sales) AS "t0" ON "t"."c_customer_sk" = "t0"."ss_customer_sk") AS "t1"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t2" ON "t1"."ss_sold_date_sk" = "t2"."d_date_sk"
GROUP BY "t1"."c_customer_id", "t1"."c_first_name", "t1"."c_last_name", "t1"."c_preferred_cust_flag", "t1"."c_birth_country", "t1"."c_login", "t1"."c_email_address", "t2"."d_year"
UNION ALL
SELECT "t8"."c_customer_id" AS "customer_id", "t8"."c_first_name" AS "customer_first_name", "t8"."c_last_name" AS "customer_last_name", "t8"."c_preferred_cust_flag" AS "customer_preferred_cust_flag", "t8"."c_birth_country" AS "customer_birth_country", "t8"."c_login" AS "customer_login", "t8"."c_email_address" AS "customer_email_address", "t9"."d_year" AS "dyear", SUM("t8"."/") AS "year_total", 'c' AS "sale_type"
FROM (SELECT "t6"."c_customer_id", "t6"."c_first_name", "t6"."c_last_name", "t6"."c_preferred_cust_flag", "t6"."c_birth_country", "t6"."c_login", "t6"."c_email_address", "t7"."cs_sold_date_sk", "t7"."/"
FROM (SELECT "c_customer_sk", "c_customer_id", "c_first_name", "c_last_name", "c_preferred_cust_flag", "c_birth_country", "c_login", "c_email_address"
FROM '/mnt/disks/tpcds/parquet/customer.parquet' AS customer) AS "t6"
INNER JOIN (SELECT "cs_sold_date_sk", "cs_bill_customer_sk", ("cs_ext_list_price" - "cs_ext_wholesale_cost" - "cs_ext_discount_amt" + "cs_ext_sales_price") / 2 AS "/"
FROM '/mnt/disks/tpcds/parquet/catalog_sales.parquet' AS catalog_sales) AS "t7" ON "t6"."c_customer_sk" = "t7"."cs_bill_customer_sk") AS "t8"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t9" ON "t8"."cs_sold_date_sk" = "t9"."d_date_sk"
GROUP BY "t8"."c_customer_id", "t8"."c_first_name", "t8"."c_last_name", "t8"."c_preferred_cust_flag", "t8"."c_birth_country", "t8"."c_login", "t8"."c_email_address", "t9"."d_year") AS "t"
UNION ALL
SELECT "t16"."c_customer_id" AS "customer_id", "t16"."c_first_name" AS "customer_first_name", "t16"."c_last_name" AS "customer_last_name", "t16"."c_preferred_cust_flag" AS "customer_preferred_cust_flag", "t16"."c_birth_country" AS "customer_birth_country", "t16"."c_login" AS "customer_login", "t16"."c_email_address" AS "customer_email_address", "t17"."d_year" AS "dyear", SUM("t16"."/") AS "year_total", 'w' AS "sale_type"
FROM (SELECT "t14"."c_customer_id", "t14"."c_first_name", "t14"."c_last_name", "t14"."c_preferred_cust_flag", "t14"."c_birth_country", "t14"."c_login", "t14"."c_email_address", "t15"."ws_sold_date_sk", "t15"."/"
FROM (SELECT "c_customer_sk", "c_customer_id", "c_first_name", "c_last_name", "c_preferred_cust_flag", "c_birth_country", "c_login", "c_email_address"
FROM '/mnt/disks/tpcds/parquet/customer.parquet' AS customer) AS "t14"
INNER JOIN (SELECT "ws_sold_date_sk", "ws_bill_customer_sk", ("ws_ext_list_price" - "ws_ext_wholesale_cost" - "ws_ext_discount_amt" + "ws_ext_sales_price") / 2 AS "/"
FROM '/mnt/disks/tpcds/parquet/web_sales.parquet' AS web_sales) AS "t15" ON "t14"."c_customer_sk" = "t15"."ws_bill_customer_sk") AS "t16"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t17" ON "t16"."ws_sold_date_sk" = "t17"."d_date_sk"
GROUP BY "t16"."c_customer_id", "t16"."c_first_name", "t16"."c_last_name", "t16"."c_preferred_cust_flag", "t16"."c_birth_country", "t16"."c_login", "t16"."c_email_address", "t17"."d_year"
;
CREATE TABLE duck_table_04_1 AS SELECT "t18"."customer_id0" AS "customer_id", "t18"."customer_first_name0" AS "customer_first_name", "t18"."customer_last_name0" AS "customer_last_name", "t18"."customer_preferred_cust_flag0" AS "customer_preferred_cust_flag"
FROM (SELECT "t13"."customer_id", "t13"."customer_id0", "t13"."customer_first_name0", "t13"."customer_last_name0", "t13"."customer_preferred_cust_flag0", "t16"."year_total" AS "year_total3", "t13"."CASE", "t16".">"
FROM (SELECT "t9"."customer_id", "t9"."customer_id0", "t9"."customer_first_name0", "t9"."customer_last_name0", "t9"."customer_preferred_cust_flag0", CASE WHEN "t9".">" THEN "t12"."year_total" / "t9"."year_total1" ELSE NULL END AS "CASE"
FROM (SELECT "t5"."customer_id", "t5"."customer_id0", "t5"."customer_first_name0", "t5"."customer_last_name0", "t5"."customer_preferred_cust_flag0", "t8"."year_total" AS "year_total1", "t8".">", "t5"."CASE"
FROM (SELECT "t1"."customer_id", "t4"."customer_id" AS "customer_id0", "t4"."customer_first_name" AS "customer_first_name0", "t4"."customer_last_name" AS "customer_last_name0", "t4"."customer_preferred_cust_flag" AS "customer_preferred_cust_flag0", CASE WHEN "t1".">" THEN "t4"."year_total" / "t1"."year_total" ELSE NULL END AS "CASE"
FROM (SELECT "customer_id", "year_total", "year_total" > 0 AS ">"
FROM "duck_table_04_0"
WHERE "sale_type" = 's' AND "dyear" = 2001 AND "year_total" > 0) AS "t1"
INNER JOIN (SELECT "customer_id", "customer_first_name", "customer_last_name", "customer_preferred_cust_flag", "year_total"
FROM "duck_table_04_0"
WHERE "sale_type" = 's' AND "dyear" = 2001 + 1) AS "t4" ON "t1"."customer_id" = "t4"."customer_id") AS "t5"
INNER JOIN (SELECT "customer_id", "year_total", "year_total" > 0 AS ">"
FROM "duck_table_04_0"
WHERE "sale_type" = 'c' AND "dyear" = 2001 AND "year_total" > 0) AS "t8" ON "t5"."customer_id" = "t8"."customer_id") AS "t9"
INNER JOIN (SELECT "customer_id", "year_total"
FROM "duck_table_04_0"
WHERE "sale_type" = 'c' AND "dyear" = 2001 + 1) AS "t12" ON "t9"."customer_id" = "t12"."customer_id" AND CASE WHEN "t9".">" THEN "t12"."year_total" / "t9"."year_total1" ELSE NULL END > "t9"."CASE") AS "t13"
INNER JOIN (SELECT "customer_id", "year_total", "year_total" > 0 AS ">"
FROM "duck_table_04_0"
WHERE "sale_type" = 'w' AND "dyear" = 2001 AND "year_total" > 0) AS "t16" ON "t13"."customer_id" = "t16"."customer_id") AS "t18"
INNER JOIN (SELECT "customer_id", "year_total"
FROM "duck_table_04_0"
WHERE "sale_type" = 'w' AND "dyear" = 2001 + 1) AS "t21" ON "t18"."customer_id" = "t21"."customer_id" AND "t18"."CASE" > CASE WHEN "t18".">" THEN CAST("t21"."year_total" / "t18"."year_total3" AS DECIMAL(19, 0)) ELSE NULL END
;
SELECT *
FROM "duck_table_04_1"
ORDER BY "customer_id" NULLS FIRST, "customer_first_name" NULLS FIRST, "customer_last_name" NULLS FIRST, "customer_preferred_cust_flag" NULLS FIRST
FETCH NEXT 100 ROWS ONLY
;
