CREATE TABLE duck_table_11_0 AS SELECT "t1"."c_customer_id" AS "customer_id", "t1"."c_first_name" AS "customer_first_name", "t1"."c_last_name" AS "customer_last_name", "t1"."c_preferred_cust_flag" AS "customer_preferred_cust_flag", "t1"."c_birth_country" AS "customer_birth_country", "t1"."c_login" AS "customer_login", "t1"."c_email_address" AS "customer_email_address", "t2"."d_year" AS "dyear", SUM("t1"."-") AS "year_total", 's' AS "sale_type"
FROM (SELECT "t"."c_customer_id", "t"."c_first_name", "t"."c_last_name", "t"."c_preferred_cust_flag", "t"."c_birth_country", "t"."c_login", "t"."c_email_address", "t0"."ss_sold_date_sk", "t0"."-"
FROM (SELECT "c_customer_sk", "c_customer_id", "c_first_name", "c_last_name", "c_preferred_cust_flag", "c_birth_country", "c_login", "c_email_address"
FROM '/mnt/disks/tpcds/parquet/customer.parquet' AS customer) AS "t"
INNER JOIN (SELECT "ss_sold_date_sk", "ss_customer_sk", "ss_ext_list_price" - "ss_ext_discount_amt" AS "-"
FROM '/mnt/disks/tpcds/parquet/store_sales.parquet' AS store_sales) AS "t0" ON "t"."c_customer_sk" = "t0"."ss_customer_sk") AS "t1"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t2" ON "t1"."ss_sold_date_sk" = "t2"."d_date_sk"
GROUP BY "t1"."c_customer_id", "t1"."c_first_name", "t1"."c_last_name", "t1"."c_preferred_cust_flag", "t1"."c_birth_country", "t1"."c_login", "t1"."c_email_address", "t2"."d_year"
UNION ALL
SELECT "t8"."c_customer_id" AS "customer_id", "t8"."c_first_name" AS "customer_first_name", "t8"."c_last_name" AS "customer_last_name", "t8"."c_preferred_cust_flag" AS "customer_preferred_cust_flag", "t8"."c_birth_country" AS "customer_birth_country", "t8"."c_login" AS "customer_login", "t8"."c_email_address" AS "customer_email_address", "t9"."d_year" AS "dyear", SUM("t8"."-") AS "year_total", 'w' AS "sale_type"
FROM (SELECT "t6"."c_customer_id", "t6"."c_first_name", "t6"."c_last_name", "t6"."c_preferred_cust_flag", "t6"."c_birth_country", "t6"."c_login", "t6"."c_email_address", "t7"."ws_sold_date_sk", "t7"."-"
FROM (SELECT "c_customer_sk", "c_customer_id", "c_first_name", "c_last_name", "c_preferred_cust_flag", "c_birth_country", "c_login", "c_email_address"
FROM '/mnt/disks/tpcds/parquet/customer.parquet' AS customer) AS "t6"
INNER JOIN (SELECT "ws_sold_date_sk", "ws_bill_customer_sk", "ws_ext_list_price" - "ws_ext_discount_amt" AS "-"
FROM '/mnt/disks/tpcds/parquet/web_sales.parquet' AS web_sales) AS "t7" ON "t6"."c_customer_sk" = "t7"."ws_bill_customer_sk") AS "t8"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t9" ON "t8"."ws_sold_date_sk" = "t9"."d_date_sk"
GROUP BY "t8"."c_customer_id", "t8"."c_first_name", "t8"."c_last_name", "t8"."c_preferred_cust_flag", "t8"."c_birth_country", "t8"."c_login", "t8"."c_email_address", "t9"."d_year"
;
CREATE TABLE duck_table_11_1 AS SELECT "t1"."c_customer_id" AS "customer_id", "t1"."c_first_name" AS "customer_first_name", "t1"."c_last_name" AS "customer_last_name", "t1"."c_preferred_cust_flag" AS "customer_preferred_cust_flag", "t1"."c_birth_country" AS "customer_birth_country", "t1"."c_login" AS "customer_login", "t1"."c_email_address" AS "customer_email_address", "t2"."d_year" AS "dyear", SUM("t1"."-") AS "year_total", 's' AS "sale_type"
FROM (SELECT "t"."c_customer_id", "t"."c_first_name", "t"."c_last_name", "t"."c_preferred_cust_flag", "t"."c_birth_country", "t"."c_login", "t"."c_email_address", "t0"."ss_sold_date_sk", "t0"."-"
FROM (SELECT "c_customer_sk", "c_customer_id", "c_first_name", "c_last_name", "c_preferred_cust_flag", "c_birth_country", "c_login", "c_email_address"
FROM '/mnt/disks/tpcds/parquet/customer.parquet' AS customer) AS "t"
INNER JOIN (SELECT "ss_sold_date_sk", "ss_customer_sk", "ss_ext_list_price" - "ss_ext_discount_amt" AS "-"
FROM '/mnt/disks/tpcds/parquet/store_sales.parquet' AS store_sales) AS "t0" ON "t"."c_customer_sk" = "t0"."ss_customer_sk") AS "t1"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t2" ON "t1"."ss_sold_date_sk" = "t2"."d_date_sk"
GROUP BY "t1"."c_customer_id", "t1"."c_first_name", "t1"."c_last_name", "t1"."c_preferred_cust_flag", "t1"."c_birth_country", "t1"."c_login", "t1"."c_email_address", "t2"."d_year"
UNION ALL
SELECT "t8"."c_customer_id" AS "customer_id", "t8"."c_first_name" AS "customer_first_name", "t8"."c_last_name" AS "customer_last_name", "t8"."c_preferred_cust_flag" AS "customer_preferred_cust_flag", "t8"."c_birth_country" AS "customer_birth_country", "t8"."c_login" AS "customer_login", "t8"."c_email_address" AS "customer_email_address", "t9"."d_year" AS "dyear", SUM("t8"."-") AS "year_total", 'w' AS "sale_type"
FROM (SELECT "t6"."c_customer_id", "t6"."c_first_name", "t6"."c_last_name", "t6"."c_preferred_cust_flag", "t6"."c_birth_country", "t6"."c_login", "t6"."c_email_address", "t7"."ws_sold_date_sk", "t7"."-"
FROM (SELECT "c_customer_sk", "c_customer_id", "c_first_name", "c_last_name", "c_preferred_cust_flag", "c_birth_country", "c_login", "c_email_address"
FROM '/mnt/disks/tpcds/parquet/customer.parquet' AS customer) AS "t6"
INNER JOIN (SELECT "ws_sold_date_sk", "ws_bill_customer_sk", "ws_ext_list_price" - "ws_ext_discount_amt" AS "-"
FROM '/mnt/disks/tpcds/parquet/web_sales.parquet' AS web_sales) AS "t7" ON "t6"."c_customer_sk" = "t7"."ws_bill_customer_sk") AS "t8"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t9" ON "t8"."ws_sold_date_sk" = "t9"."d_date_sk"
GROUP BY "t8"."c_customer_id", "t8"."c_first_name", "t8"."c_last_name", "t8"."c_preferred_cust_flag", "t8"."c_birth_country", "t8"."c_login", "t8"."c_email_address", "t9"."d_year"
;
SELECT "t10"."customer_id0" AS "customer_id", "t10"."customer_first_name0" AS "customer_first_name", "t10"."customer_last_name0" AS "customer_last_name", "t10"."customer_preferred_cust_flag0" AS "customer_preferred_cust_flag"
FROM (SELECT "t5"."customer_id", "t5"."customer_id0", "t5"."customer_first_name0", "t5"."customer_last_name0", "t5"."customer_preferred_cust_flag0", "t8"."year_total" AS "year_total1", "t8".">", CASE WHEN "t5".">" THEN "t5"."/" ELSE 0.0 END AS "CASE"
FROM (SELECT "t1"."customer_id", "t4"."customer_id" AS "customer_id0", "t4"."customer_first_name" AS "customer_first_name0", "t4"."customer_last_name" AS "customer_last_name0", "t4"."customer_preferred_cust_flag" AS "customer_preferred_cust_flag0", "t1".">", "t4"."*" / "t1"."year_total" AS "/"
FROM (SELECT "customer_id", "year_total", "year_total" > 0 AS ">"
FROM "duck_table_11_1"
WHERE "sale_type" = 's' AND "dyear" = 2001 AND "year_total" > 0) AS "t1"
INNER JOIN (SELECT "customer_id", "customer_first_name", "customer_last_name", "customer_preferred_cust_flag", "year_total" * 1.0000 AS "*"
FROM "duck_table_11_1"
WHERE "sale_type" = 's' AND "dyear" = 2001 + 1) AS "t4" ON "t1"."customer_id" = "t4"."customer_id") AS "t5"
INNER JOIN (SELECT "customer_id", "year_total", "year_total" > 0 AS ">"
FROM "duck_table_11_1"
WHERE "sale_type" = 'w' AND "dyear" = 2001 AND "year_total" > 0) AS "t8" ON "t5"."customer_id" = "t8"."customer_id") AS "t10"
INNER JOIN (SELECT "customer_id", "year_total" * 1.0000 AS "*"
FROM "duck_table_11_1"
WHERE "sale_type" = 'w' AND "dyear" = 2001 + 1) AS "t13" ON "t10"."customer_id" = "t13"."customer_id" AND CASE WHEN "t10".">" THEN "t13"."*" / "t10"."year_total1" ELSE 0.0 END > "t10"."CASE"
ORDER BY "t10"."customer_id0" NULLS FIRST, "t10"."customer_first_name0" NULLS FIRST, "t10"."customer_last_name0" NULLS FIRST, "t10"."customer_preferred_cust_flag0" NULLS FIRST
FETCH NEXT 100 ROWS ONLY
;
