SELECT "t41"."product_name", "t41"."store_name", "t41"."store_zip", "t41"."b_street_number", "t41"."b_street_name", "t41"."b_city", "t41"."b_zip", "t41"."c_street_number", "t41"."c_street_name", "t41"."c_city", "t41"."c_zip", "t41"."syear" AS "cs1syear", "t41"."cnt" AS "cs1cnt", "t41"."s1" AS "s11", "t41"."s2" AS "s21", "t41"."s3" AS "s31", "t84"."s1" AS "s12", "t84"."s2" AS "s22", "t84"."s3" AS "s32", "t84"."syear", "t84"."cnt"
FROM (SELECT "t37"."i_product_name" AS "product_name", "t37"."i_item_sk" AS "item_sk", "t34"."s_store_name" AS "store_name", "t34"."s_zip" AS "store_zip", "t34"."ca_street_number" AS "b_street_number", "t34"."ca_street_name" AS "b_street_name", "t34"."ca_city" AS "b_city", "t34"."ca_zip" AS "b_zip", "t34"."ca_street_number0" AS "c_street_number", "t34"."ca_street_name0" AS "c_street_name", "t34"."ca_city0" AS "c_city", "t34"."ca_zip0" AS "c_zip", "t34"."d_year" AS "syear", COUNT(*) AS "cnt", SUM("t34"."ss_wholesale_cost") AS "s1", SUM("t34"."ss_list_price") AS "s2", SUM("t34"."ss_coupon_amt") AS "s3"
FROM (SELECT "t32"."ss_item_sk", "t32"."ss_wholesale_cost", "t32"."ss_list_price", "t32"."ss_coupon_amt", "t32"."d_year", "t32"."d_year0", "t32"."d_year1", "t32"."s_store_name", "t32"."s_zip", "t32"."ca_street_number", "t32"."ca_street_name", "t32"."ca_city", "t32"."ca_zip", "t32"."ca_street_number0", "t32"."ca_street_name0", "t32"."ca_city0", "t32"."ca_zip0"
FROM (SELECT "t30"."ss_item_sk", "t30"."ss_wholesale_cost", "t30"."ss_list_price", "t30"."ss_coupon_amt", "t30"."d_year", "t30"."d_year0", "t30"."d_year1", "t30"."s_store_name", "t30"."s_zip", "t30"."hd_income_band_sk0", "t30"."ca_street_number", "t30"."ca_street_name", "t30"."ca_city", "t30"."ca_zip", "t30"."ca_street_number0", "t30"."ca_street_name0", "t30"."ca_city0", "t30"."ca_zip0"
FROM (SELECT "t28"."ss_item_sk", "t28"."ss_wholesale_cost", "t28"."ss_list_price", "t28"."ss_coupon_amt", "t28"."d_year", "t28"."d_year0", "t28"."d_year1", "t28"."s_store_name", "t28"."s_zip", "t28"."hd_income_band_sk", "t28"."hd_income_band_sk0", "t28"."ca_street_number", "t28"."ca_street_name", "t28"."ca_city", "t28"."ca_zip", "t29"."ca_street_number" AS "ca_street_number0", "t29"."ca_street_name" AS "ca_street_name0", "t29"."ca_city" AS "ca_city0", "t29"."ca_zip" AS "ca_zip0"
FROM (SELECT "t26"."ss_item_sk", "t26"."ss_wholesale_cost", "t26"."ss_list_price", "t26"."ss_coupon_amt", "t26"."d_year", "t26"."d_year0", "t26"."d_year1", "t26"."s_store_name", "t26"."s_zip", "t26"."c_current_addr_sk", "t26"."hd_income_band_sk", "t26"."hd_income_band_sk0", "t27"."ca_street_number", "t27"."ca_street_name", "t27"."ca_city", "t27"."ca_zip"
FROM (SELECT "t24"."ss_item_sk", "t24"."ss_addr_sk", "t24"."ss_wholesale_cost", "t24"."ss_list_price", "t24"."ss_coupon_amt", "t24"."d_year", "t24"."d_year0", "t24"."d_year1", "t24"."s_store_name", "t24"."s_zip", "t24"."c_current_addr_sk", "t24"."hd_income_band_sk", "t25"."hd_income_band_sk" AS "hd_income_band_sk0"
FROM (SELECT "t22"."ss_item_sk", "t22"."ss_addr_sk", "t22"."ss_wholesale_cost", "t22"."ss_list_price", "t22"."ss_coupon_amt", "t22"."d_year", "t22"."d_year0", "t22"."d_year1", "t22"."s_store_name", "t22"."s_zip", "t22"."c_current_hdemo_sk", "t22"."c_current_addr_sk", "t23"."hd_income_band_sk"
FROM (SELECT "t20"."ss_item_sk", "t20"."ss_hdemo_sk", "t20"."ss_addr_sk", "t20"."ss_wholesale_cost", "t20"."ss_list_price", "t20"."ss_coupon_amt", "t20"."d_year", "t20"."d_year0", "t20"."d_year1", "t20"."s_store_name", "t20"."s_zip", "t20"."c_current_hdemo_sk", "t20"."c_current_addr_sk"
FROM (SELECT "t18"."ss_item_sk", "t18"."ss_hdemo_sk", "t18"."ss_addr_sk", "t18"."ss_promo_sk", "t18"."ss_wholesale_cost", "t18"."ss_list_price", "t18"."ss_coupon_amt", "t18"."d_year", "t18"."d_year0", "t18"."d_year1", "t18"."s_store_name", "t18"."s_zip", "t18"."c_current_hdemo_sk", "t18"."c_current_addr_sk"
FROM (SELECT "t16"."ss_item_sk", "t16"."ss_hdemo_sk", "t16"."ss_addr_sk", "t16"."ss_promo_sk", "t16"."ss_wholesale_cost", "t16"."ss_list_price", "t16"."ss_coupon_amt", "t16"."d_year", "t16"."d_year0", "t16"."d_year1", "t16"."s_store_name", "t16"."s_zip", "t16"."c_current_cdemo_sk", "t16"."c_current_hdemo_sk", "t16"."c_current_addr_sk", "t17"."cd_marital_status"
FROM (SELECT "t14"."ss_item_sk", "t14"."ss_cdemo_sk", "t14"."ss_hdemo_sk", "t14"."ss_addr_sk", "t14"."ss_promo_sk", "t14"."ss_wholesale_cost", "t14"."ss_list_price", "t14"."ss_coupon_amt", "t14"."d_year", "t14"."d_year0", "t14"."d_year1", "t14"."s_store_name", "t14"."s_zip", "t15"."c_current_cdemo_sk", "t15"."c_current_hdemo_sk", "t15"."c_current_addr_sk"
FROM (SELECT "t10"."ss_item_sk", "t10"."ss_customer_sk", "t10"."ss_cdemo_sk", "t10"."ss_hdemo_sk", "t10"."ss_addr_sk", "t10"."ss_promo_sk", "t10"."ss_wholesale_cost", "t10"."ss_list_price", "t10"."ss_coupon_amt", "t10"."d_year", "t11"."d_date_sk" AS "d_date_sk0", "t11"."d_year" AS "d_year0", "t12"."d_date_sk" AS "d_date_sk1", "t12"."d_year" AS "d_year1", "t13"."s_store_name", "t13"."s_zip"
FROM (SELECT "t8"."ss_item_sk", "t8"."ss_customer_sk", "t8"."ss_cdemo_sk", "t8"."ss_hdemo_sk", "t8"."ss_addr_sk", "t8"."ss_store_sk", "t8"."ss_promo_sk", "t8"."ss_wholesale_cost", "t8"."ss_list_price", "t8"."ss_coupon_amt", "t9"."d_year"
FROM (SELECT "t1"."ss_sold_date_sk", "t1"."ss_item_sk", "t1"."ss_customer_sk", "t1"."ss_cdemo_sk", "t1"."ss_hdemo_sk", "t1"."ss_addr_sk", "t1"."ss_store_sk", "t1"."ss_promo_sk", "t1"."ss_wholesale_cost", "t1"."ss_list_price", "t1"."ss_coupon_amt"
FROM (SELECT "t"."ss_sold_date_sk", "t"."ss_item_sk", "t"."ss_customer_sk", "t"."ss_cdemo_sk", "t"."ss_hdemo_sk", "t"."ss_addr_sk", "t"."ss_store_sk", "t"."ss_promo_sk", "t"."ss_wholesale_cost", "t"."ss_list_price", "t"."ss_coupon_amt"
FROM (SELECT "ss_sold_date_sk", "ss_item_sk", "ss_customer_sk", "ss_cdemo_sk", "ss_hdemo_sk", "ss_addr_sk", "ss_store_sk", "ss_promo_sk", "ss_ticket_number", "ss_wholesale_cost", "ss_list_price", "ss_coupon_amt"
FROM '/mnt/disks/tpcds/parquet/store_sales.parquet' AS store_sales) AS "t"
INNER JOIN (SELECT "sr_item_sk", "sr_ticket_number"
FROM '/mnt/disks/tpcds/parquet/store_returns.parquet' AS store_returns) AS "t0" ON "t"."ss_item_sk" = "t0"."sr_item_sk" AND "t"."ss_ticket_number" = "t0"."sr_ticket_number") AS "t1"
INNER JOIN (SELECT "t2"."cs_item_sk"
FROM (SELECT "cs_item_sk", "cs_order_number", "cs_ext_list_price"
FROM '/mnt/disks/tpcds/parquet/catalog_sales.parquet' AS catalog_sales) AS "t2"
INNER JOIN (SELECT "cr_item_sk", "cr_order_number", "cr_refunded_cash" + "cr_reversed_charge" + "cr_store_credit" AS "+"
FROM '/mnt/disks/tpcds/parquet/catalog_returns.parquet' AS catalog_returns) AS "t3" ON "t2"."cs_item_sk" = "t3"."cr_item_sk" AND "t2"."cs_order_number" = "t3"."cr_order_number"
GROUP BY "t2"."cs_item_sk"
HAVING SUM("t2"."cs_ext_list_price") > 2 * SUM("t3"."+")) AS "t7" ON "t1"."ss_item_sk" = "t7"."cs_item_sk") AS "t8"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t9" ON "t8"."ss_sold_date_sk" = "t9"."d_date_sk") AS "t10",
(SELECT "d_date_sk", "d_year"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t11",
(SELECT "d_date_sk", "d_year"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t12"
INNER JOIN (SELECT "s_store_sk", "s_store_name", "s_zip"
FROM '/mnt/disks/tpcds/parquet/store.parquet' AS store) AS "t13" ON "t10"."ss_store_sk" = "t13"."s_store_sk") AS "t14"
INNER JOIN (SELECT "c_customer_sk", "c_current_cdemo_sk", "c_current_hdemo_sk", "c_current_addr_sk", "c_first_shipto_date_sk", "c_first_sales_date_sk"
FROM '/mnt/disks/tpcds/parquet/customer.parquet' AS customer) AS "t15" ON "t14"."ss_customer_sk" = "t15"."c_customer_sk" AND "t14"."d_date_sk0" = "t15"."c_first_sales_date_sk" AND "t14"."d_date_sk1" = "t15"."c_first_shipto_date_sk") AS "t16"
INNER JOIN (SELECT "cd_demo_sk", "cd_marital_status"
FROM '/mnt/disks/tpcds/parquet/customer_demographics.parquet' AS customer_demographics) AS "t17" ON "t16"."ss_cdemo_sk" = "t17"."cd_demo_sk") AS "t18"
INNER JOIN (SELECT "cd_demo_sk", "cd_marital_status"
FROM '/mnt/disks/tpcds/parquet/customer_demographics.parquet' AS customer_demographics) AS "t19" ON "t18"."c_current_cdemo_sk" = "t19"."cd_demo_sk" AND "t18"."cd_marital_status" <> "t19"."cd_marital_status") AS "t20"
INNER JOIN (SELECT "p_promo_sk"
FROM '/mnt/disks/tpcds/parquet/promotion.parquet' AS promotion) AS "t21" ON "t20"."ss_promo_sk" = "t21"."p_promo_sk") AS "t22"
INNER JOIN (SELECT "hd_demo_sk", "hd_income_band_sk"
FROM '/mnt/disks/tpcds/parquet/household_demographics.parquet' AS household_demographics) AS "t23" ON "t22"."ss_hdemo_sk" = "t23"."hd_demo_sk") AS "t24"
INNER JOIN (SELECT "hd_demo_sk", "hd_income_band_sk"
FROM '/mnt/disks/tpcds/parquet/household_demographics.parquet' AS household_demographics) AS "t25" ON "t24"."c_current_hdemo_sk" = "t25"."hd_demo_sk") AS "t26"
INNER JOIN (SELECT "ca_address_sk", "ca_street_number", "ca_street_name", "ca_city", "ca_zip"
FROM '/mnt/disks/tpcds/parquet/customer_address.parquet' AS customer_address) AS "t27" ON "t26"."ss_addr_sk" = "t27"."ca_address_sk") AS "t28"
INNER JOIN (SELECT "ca_address_sk", "ca_street_number", "ca_street_name", "ca_city", "ca_zip"
FROM '/mnt/disks/tpcds/parquet/customer_address.parquet' AS customer_address) AS "t29" ON "t28"."c_current_addr_sk" = "t29"."ca_address_sk") AS "t30"
INNER JOIN (SELECT "ib_income_band_sk"
FROM '/mnt/disks/tpcds/parquet/income_band.parquet' AS income_band) AS "t31" ON "t30"."hd_income_band_sk" = "t31"."ib_income_band_sk") AS "t32"
INNER JOIN (SELECT "ib_income_band_sk"
FROM '/mnt/disks/tpcds/parquet/income_band.parquet' AS income_band) AS "t33" ON "t32"."hd_income_band_sk0" = "t33"."ib_income_band_sk") AS "t34"
INNER JOIN (SELECT "i_item_sk", "i_product_name"
FROM '/mnt/disks/tpcds/parquet/item.parquet' AS item
WHERE "i_color" IN ('burlywood', 'floral', 'indian', 'medium', 'purple', 'spring') AND "i_current_price" >= 64 AND "i_current_price" <= 64 + 10 AND "i_current_price" >= 64 + 1 AND "i_current_price" <= 64 + 15) AS "t37" ON "t34"."ss_item_sk" = "t37"."i_item_sk"
GROUP BY "t37"."i_product_name", "t37"."i_item_sk", "t34"."s_store_name", "t34"."s_zip", "t34"."ca_street_number", "t34"."ca_street_name", "t34"."ca_city", "t34"."ca_zip", "t34"."ca_street_number0", "t34"."ca_street_name0", "t34"."ca_city0", "t34"."ca_zip0", "t34"."d_year", "t34"."d_year0", "t34"."d_year1"
HAVING "t34"."d_year" = 1999) AS "t41"
INNER JOIN (SELECT "t80"."i_item_sk" AS "item_sk", "t77"."s_store_name" AS "store_name", "t77"."s_zip" AS "store_zip", "t77"."d_year" AS "syear", COUNT(*) AS "cnt", SUM("t77"."ss_wholesale_cost") AS "s1", SUM("t77"."ss_list_price") AS "s2", SUM("t77"."ss_coupon_amt") AS "s3"
FROM (SELECT "t75"."ss_item_sk", "t75"."ss_wholesale_cost", "t75"."ss_list_price", "t75"."ss_coupon_amt", "t75"."d_year", "t75"."d_year0", "t75"."d_year1", "t75"."s_store_name", "t75"."s_zip", "t75"."ca_street_number", "t75"."ca_street_name", "t75"."ca_city", "t75"."ca_zip", "t75"."ca_street_number0", "t75"."ca_street_name0", "t75"."ca_city0", "t75"."ca_zip0"
FROM (SELECT "t73"."ss_item_sk", "t73"."ss_wholesale_cost", "t73"."ss_list_price", "t73"."ss_coupon_amt", "t73"."d_year", "t73"."d_year0", "t73"."d_year1", "t73"."s_store_name", "t73"."s_zip", "t73"."hd_income_band_sk0", "t73"."ca_street_number", "t73"."ca_street_name", "t73"."ca_city", "t73"."ca_zip", "t73"."ca_street_number0", "t73"."ca_street_name0", "t73"."ca_city0", "t73"."ca_zip0"
FROM (SELECT "t71"."ss_item_sk", "t71"."ss_wholesale_cost", "t71"."ss_list_price", "t71"."ss_coupon_amt", "t71"."d_year", "t71"."d_year0", "t71"."d_year1", "t71"."s_store_name", "t71"."s_zip", "t71"."hd_income_band_sk", "t71"."hd_income_band_sk0", "t71"."ca_street_number", "t71"."ca_street_name", "t71"."ca_city", "t71"."ca_zip", "t72"."ca_street_number" AS "ca_street_number0", "t72"."ca_street_name" AS "ca_street_name0", "t72"."ca_city" AS "ca_city0", "t72"."ca_zip" AS "ca_zip0"
FROM (SELECT "t69"."ss_item_sk", "t69"."ss_wholesale_cost", "t69"."ss_list_price", "t69"."ss_coupon_amt", "t69"."d_year", "t69"."d_year0", "t69"."d_year1", "t69"."s_store_name", "t69"."s_zip", "t69"."c_current_addr_sk", "t69"."hd_income_band_sk", "t69"."hd_income_band_sk0", "t70"."ca_street_number", "t70"."ca_street_name", "t70"."ca_city", "t70"."ca_zip"
FROM (SELECT "t67"."ss_item_sk", "t67"."ss_addr_sk", "t67"."ss_wholesale_cost", "t67"."ss_list_price", "t67"."ss_coupon_amt", "t67"."d_year", "t67"."d_year0", "t67"."d_year1", "t67"."s_store_name", "t67"."s_zip", "t67"."c_current_addr_sk", "t67"."hd_income_band_sk", "t68"."hd_income_band_sk" AS "hd_income_band_sk0"
FROM (SELECT "t65"."ss_item_sk", "t65"."ss_addr_sk", "t65"."ss_wholesale_cost", "t65"."ss_list_price", "t65"."ss_coupon_amt", "t65"."d_year", "t65"."d_year0", "t65"."d_year1", "t65"."s_store_name", "t65"."s_zip", "t65"."c_current_hdemo_sk", "t65"."c_current_addr_sk", "t66"."hd_income_band_sk"
FROM (SELECT "t63"."ss_item_sk", "t63"."ss_hdemo_sk", "t63"."ss_addr_sk", "t63"."ss_wholesale_cost", "t63"."ss_list_price", "t63"."ss_coupon_amt", "t63"."d_year", "t63"."d_year0", "t63"."d_year1", "t63"."s_store_name", "t63"."s_zip", "t63"."c_current_hdemo_sk", "t63"."c_current_addr_sk"
FROM (SELECT "t61"."ss_item_sk", "t61"."ss_hdemo_sk", "t61"."ss_addr_sk", "t61"."ss_promo_sk", "t61"."ss_wholesale_cost", "t61"."ss_list_price", "t61"."ss_coupon_amt", "t61"."d_year", "t61"."d_year0", "t61"."d_year1", "t61"."s_store_name", "t61"."s_zip", "t61"."c_current_hdemo_sk", "t61"."c_current_addr_sk"
FROM (SELECT "t59"."ss_item_sk", "t59"."ss_hdemo_sk", "t59"."ss_addr_sk", "t59"."ss_promo_sk", "t59"."ss_wholesale_cost", "t59"."ss_list_price", "t59"."ss_coupon_amt", "t59"."d_year", "t59"."d_year0", "t59"."d_year1", "t59"."s_store_name", "t59"."s_zip", "t59"."c_current_cdemo_sk", "t59"."c_current_hdemo_sk", "t59"."c_current_addr_sk", "t60"."cd_marital_status"
FROM (SELECT "t57"."ss_item_sk", "t57"."ss_cdemo_sk", "t57"."ss_hdemo_sk", "t57"."ss_addr_sk", "t57"."ss_promo_sk", "t57"."ss_wholesale_cost", "t57"."ss_list_price", "t57"."ss_coupon_amt", "t57"."d_year", "t57"."d_year0", "t57"."d_year1", "t57"."s_store_name", "t57"."s_zip", "t58"."c_current_cdemo_sk", "t58"."c_current_hdemo_sk", "t58"."c_current_addr_sk"
FROM (SELECT "t53"."ss_item_sk", "t53"."ss_customer_sk", "t53"."ss_cdemo_sk", "t53"."ss_hdemo_sk", "t53"."ss_addr_sk", "t53"."ss_promo_sk", "t53"."ss_wholesale_cost", "t53"."ss_list_price", "t53"."ss_coupon_amt", "t53"."d_year", "t54"."d_date_sk" AS "d_date_sk0", "t54"."d_year" AS "d_year0", "t55"."d_date_sk" AS "d_date_sk1", "t55"."d_year" AS "d_year1", "t56"."s_store_name", "t56"."s_zip"
FROM (SELECT "t51"."ss_item_sk", "t51"."ss_customer_sk", "t51"."ss_cdemo_sk", "t51"."ss_hdemo_sk", "t51"."ss_addr_sk", "t51"."ss_store_sk", "t51"."ss_promo_sk", "t51"."ss_wholesale_cost", "t51"."ss_list_price", "t51"."ss_coupon_amt", "t52"."d_year"
FROM (SELECT "t44"."ss_sold_date_sk", "t44"."ss_item_sk", "t44"."ss_customer_sk", "t44"."ss_cdemo_sk", "t44"."ss_hdemo_sk", "t44"."ss_addr_sk", "t44"."ss_store_sk", "t44"."ss_promo_sk", "t44"."ss_wholesale_cost", "t44"."ss_list_price", "t44"."ss_coupon_amt"
FROM (SELECT "t42"."ss_sold_date_sk", "t42"."ss_item_sk", "t42"."ss_customer_sk", "t42"."ss_cdemo_sk", "t42"."ss_hdemo_sk", "t42"."ss_addr_sk", "t42"."ss_store_sk", "t42"."ss_promo_sk", "t42"."ss_wholesale_cost", "t42"."ss_list_price", "t42"."ss_coupon_amt"
FROM (SELECT "ss_sold_date_sk", "ss_item_sk", "ss_customer_sk", "ss_cdemo_sk", "ss_hdemo_sk", "ss_addr_sk", "ss_store_sk", "ss_promo_sk", "ss_ticket_number", "ss_wholesale_cost", "ss_list_price", "ss_coupon_amt"
FROM '/mnt/disks/tpcds/parquet/store_sales.parquet' AS store_sales) AS "t42"
INNER JOIN (SELECT "sr_item_sk", "sr_ticket_number"
FROM '/mnt/disks/tpcds/parquet/store_returns.parquet' AS store_returns) AS "t43" ON "t42"."ss_item_sk" = "t43"."sr_item_sk" AND "t42"."ss_ticket_number" = "t43"."sr_ticket_number") AS "t44"
INNER JOIN (SELECT "t45"."cs_item_sk"
FROM (SELECT "cs_item_sk", "cs_order_number", "cs_ext_list_price"
FROM '/mnt/disks/tpcds/parquet/catalog_sales.parquet' AS catalog_sales) AS "t45"
INNER JOIN (SELECT "cr_item_sk", "cr_order_number", "cr_refunded_cash" + "cr_reversed_charge" + "cr_store_credit" AS "+"
FROM '/mnt/disks/tpcds/parquet/catalog_returns.parquet' AS catalog_returns) AS "t46" ON "t45"."cs_item_sk" = "t46"."cr_item_sk" AND "t45"."cs_order_number" = "t46"."cr_order_number"
GROUP BY "t45"."cs_item_sk"
HAVING SUM("t45"."cs_ext_list_price") > 2 * SUM("t46"."+")) AS "t50" ON "t44"."ss_item_sk" = "t50"."cs_item_sk") AS "t51"
INNER JOIN (SELECT "d_date_sk", "d_year"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t52" ON "t51"."ss_sold_date_sk" = "t52"."d_date_sk") AS "t53",
(SELECT "d_date_sk", "d_year"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t54",
(SELECT "d_date_sk", "d_year"
FROM '/mnt/disks/tpcds/parquet/date_dim.parquet' AS date_dim) AS "t55"
INNER JOIN (SELECT "s_store_sk", "s_store_name", "s_zip"
FROM '/mnt/disks/tpcds/parquet/store.parquet' AS store) AS "t56" ON "t53"."ss_store_sk" = "t56"."s_store_sk") AS "t57"
INNER JOIN (SELECT "c_customer_sk", "c_current_cdemo_sk", "c_current_hdemo_sk", "c_current_addr_sk", "c_first_shipto_date_sk", "c_first_sales_date_sk"
FROM '/mnt/disks/tpcds/parquet/customer.parquet' AS customer) AS "t58" ON "t57"."ss_customer_sk" = "t58"."c_customer_sk" AND "t57"."d_date_sk0" = "t58"."c_first_sales_date_sk" AND "t57"."d_date_sk1" = "t58"."c_first_shipto_date_sk") AS "t59"
INNER JOIN (SELECT "cd_demo_sk", "cd_marital_status"
FROM '/mnt/disks/tpcds/parquet/customer_demographics.parquet' AS customer_demographics) AS "t60" ON "t59"."ss_cdemo_sk" = "t60"."cd_demo_sk") AS "t61"
INNER JOIN (SELECT "cd_demo_sk", "cd_marital_status"
FROM '/mnt/disks/tpcds/parquet/customer_demographics.parquet' AS customer_demographics) AS "t62" ON "t61"."c_current_cdemo_sk" = "t62"."cd_demo_sk" AND "t61"."cd_marital_status" <> "t62"."cd_marital_status") AS "t63"
INNER JOIN (SELECT "p_promo_sk"
FROM '/mnt/disks/tpcds/parquet/promotion.parquet' AS promotion) AS "t64" ON "t63"."ss_promo_sk" = "t64"."p_promo_sk") AS "t65"
INNER JOIN (SELECT "hd_demo_sk", "hd_income_band_sk"
FROM '/mnt/disks/tpcds/parquet/household_demographics.parquet' AS household_demographics) AS "t66" ON "t65"."ss_hdemo_sk" = "t66"."hd_demo_sk") AS "t67"
INNER JOIN (SELECT "hd_demo_sk", "hd_income_band_sk"
FROM '/mnt/disks/tpcds/parquet/household_demographics.parquet' AS household_demographics) AS "t68" ON "t67"."c_current_hdemo_sk" = "t68"."hd_demo_sk") AS "t69"
INNER JOIN (SELECT "ca_address_sk", "ca_street_number", "ca_street_name", "ca_city", "ca_zip"
FROM '/mnt/disks/tpcds/parquet/customer_address.parquet' AS customer_address) AS "t70" ON "t69"."ss_addr_sk" = "t70"."ca_address_sk") AS "t71"
INNER JOIN (SELECT "ca_address_sk", "ca_street_number", "ca_street_name", "ca_city", "ca_zip"
FROM '/mnt/disks/tpcds/parquet/customer_address.parquet' AS customer_address) AS "t72" ON "t71"."c_current_addr_sk" = "t72"."ca_address_sk") AS "t73"
INNER JOIN (SELECT "ib_income_band_sk"
FROM '/mnt/disks/tpcds/parquet/income_band.parquet' AS income_band) AS "t74" ON "t73"."hd_income_band_sk" = "t74"."ib_income_band_sk") AS "t75"
INNER JOIN (SELECT "ib_income_band_sk"
FROM '/mnt/disks/tpcds/parquet/income_band.parquet' AS income_band) AS "t76" ON "t75"."hd_income_band_sk0" = "t76"."ib_income_band_sk") AS "t77"
INNER JOIN (SELECT "i_item_sk", "i_product_name"
FROM '/mnt/disks/tpcds/parquet/item.parquet' AS item
WHERE "i_color" IN ('burlywood', 'floral', 'indian', 'medium', 'purple', 'spring') AND "i_current_price" >= 64 AND "i_current_price" <= 64 + 10 AND "i_current_price" >= 64 + 1 AND "i_current_price" <= 64 + 15) AS "t80" ON "t77"."ss_item_sk" = "t80"."i_item_sk"
GROUP BY "t80"."i_product_name", "t80"."i_item_sk", "t77"."s_store_name", "t77"."s_zip", "t77"."ca_street_number", "t77"."ca_street_name", "t77"."ca_city", "t77"."ca_zip", "t77"."ca_street_number0", "t77"."ca_street_name0", "t77"."ca_city0", "t77"."ca_zip0", "t77"."d_year", "t77"."d_year0", "t77"."d_year1"
HAVING "t77"."d_year" = 1999 + 1) AS "t84" ON "t41"."item_sk" = "t84"."item_sk" AND "t41"."cnt" >= "t84"."cnt" AND "t41"."store_name" = "t84"."store_name" AND "t41"."store_zip" = "t84"."store_zip"
ORDER BY "t41"."product_name", "t41"."store_name", "t84"."cnt", "t41"."s1", "t84"."s1"

