SELECT "src", "dst", MIN("w")
FROM (SELECT *
FROM (SELECT *
FROM (SELECT *
FROM (SELECT *
FROM (VALUES (28587302322191, 28587302322191, 0)) AS "t" ("src", "dst", "w")
UNION ALL
SELECT "t13"."p_personid" AS "src", "t16"."k_person2id" AS "dst", 1 AS "w"
FROM (SELECT "t2"."p_personid"
FROM (SELECT "t0"."p_personid", "t1"."pl_containerplaceid"
FROM (SELECT "p_personid", "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t0"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t1" ON "t0"."p_placeid" = "t1"."pl_placeid") AS "t2"
INNER JOIN (SELECT "t8"."pl_placeid"
FROM (SELECT "t4"."pl_containerplaceid"
FROM (SELECT "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t3"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t4" ON "t3"."p_placeid" = "t4"."pl_placeid") AS "t5"
INNER JOIN (SELECT "pl_placeid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place
WHERE "pl_name" IN ('China', 'India', 'Mexico')) AS "t8" ON "t5"."pl_containerplaceid" = "t8"."pl_placeid"
GROUP BY "t8"."pl_placeid"
HAVING COUNT(*) > 100) AS "t12" ON "t2"."pl_containerplaceid" = "t12"."pl_placeid") AS "t13"
INNER JOIN (SELECT "k_person1id", "k_person2id"
FROM '/mnt/disks/ldbc/parquet/knows.parquet' AS knows
WHERE "k_creationdate" >= 1354147200000 AND "k_creationdate" <= 1362441600000) AS "t16" ON "t13"."p_personid" = "t16"."k_person1id"
WHERE 1 = 1 AND CAST("t13"."p_personid" AS BIGINT) = 28587302322191) AS "t"
UNION ALL
SELECT "t39"."k_person1id" AS "src", "t57"."k_person2id" AS "dst", 2 AS "w"
FROM (SELECT "t34"."p_personid" AS "k_person1id", "t37"."k_person2id"
FROM (SELECT "t23"."p_personid"
FROM (SELECT "t21"."p_personid", "t22"."pl_containerplaceid"
FROM (SELECT "p_personid", "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t21"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t22" ON "t21"."p_placeid" = "t22"."pl_placeid") AS "t23"
INNER JOIN (SELECT "t29"."pl_placeid"
FROM (SELECT "t25"."pl_containerplaceid"
FROM (SELECT "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t24"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t25" ON "t24"."p_placeid" = "t25"."pl_placeid") AS "t26"
INNER JOIN (SELECT "pl_placeid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place
WHERE "pl_name" IN ('China', 'India', 'Mexico')) AS "t29" ON "t26"."pl_containerplaceid" = "t29"."pl_placeid"
GROUP BY "t29"."pl_placeid"
HAVING COUNT(*) > 100) AS "t33" ON "t23"."pl_containerplaceid" = "t33"."pl_placeid") AS "t34"
INNER JOIN (SELECT "k_person1id", "k_person2id"
FROM '/mnt/disks/ldbc/parquet/knows.parquet' AS knows
WHERE "k_creationdate" >= 1354147200000 AND "k_creationdate" <= 1362441600000) AS "t37" ON "t34"."p_personid" = "t37"."k_person1id"
WHERE CAST("t34"."p_personid" AS BIGINT) = 28587302322191) AS "t39"
INNER JOIN (SELECT "t53"."p_personid" AS "k_person1id", "t56"."k_person2id"
FROM (SELECT "t42"."p_personid"
FROM (SELECT "t40"."p_personid", "t41"."pl_containerplaceid"
FROM (SELECT "p_personid", "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t40"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t41" ON "t40"."p_placeid" = "t41"."pl_placeid") AS "t42"
INNER JOIN (SELECT "t48"."pl_placeid"
FROM (SELECT "t44"."pl_containerplaceid"
FROM (SELECT "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t43"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t44" ON "t43"."p_placeid" = "t44"."pl_placeid") AS "t45"
INNER JOIN (SELECT "pl_placeid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place
WHERE "pl_name" IN ('China', 'India', 'Mexico')) AS "t48" ON "t45"."pl_containerplaceid" = "t48"."pl_placeid"
GROUP BY "t48"."pl_placeid"
HAVING COUNT(*) > 100) AS "t52" ON "t42"."pl_containerplaceid" = "t52"."pl_placeid") AS "t53"
INNER JOIN (SELECT "k_person1id", "k_person2id"
FROM '/mnt/disks/ldbc/parquet/knows.parquet' AS knows
WHERE "k_creationdate" >= 1354147200000 AND "k_creationdate" <= 1362441600000) AS "t56" ON "t53"."p_personid" = "t56"."k_person1id") AS "t57" ON "t39"."k_person2id" = "t57"."k_person1id") AS "t"
UNION ALL
SELECT "t97"."k_person1id" AS "src", "t97"."k_person2id0" AS "dst", 3 AS "w"
FROM (SELECT "t78"."k_person1id", "t96"."k_person2id" AS "k_person2id0"
FROM (SELECT "t73"."p_personid" AS "k_person1id", "t76"."k_person2id"
FROM (SELECT "t62"."p_personid"
FROM (SELECT "t60"."p_personid", "t61"."pl_containerplaceid"
FROM (SELECT "p_personid", "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t60"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t61" ON "t60"."p_placeid" = "t61"."pl_placeid") AS "t62"
INNER JOIN (SELECT "t68"."pl_placeid"
FROM (SELECT "t64"."pl_containerplaceid"
FROM (SELECT "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t63"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t64" ON "t63"."p_placeid" = "t64"."pl_placeid") AS "t65"
INNER JOIN (SELECT "pl_placeid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place
WHERE "pl_name" IN ('China', 'India', 'Mexico')) AS "t68" ON "t65"."pl_containerplaceid" = "t68"."pl_placeid"
GROUP BY "t68"."pl_placeid"
HAVING COUNT(*) > 100) AS "t72" ON "t62"."pl_containerplaceid" = "t72"."pl_placeid") AS "t73"
INNER JOIN (SELECT "k_person1id", "k_person2id"
FROM '/mnt/disks/ldbc/parquet/knows.parquet' AS knows
WHERE "k_creationdate" >= 1354147200000 AND "k_creationdate" <= 1362441600000) AS "t76" ON "t73"."p_personid" = "t76"."k_person1id"
WHERE CAST("t73"."p_personid" AS BIGINT) = 28587302322191) AS "t78"
INNER JOIN (SELECT "t92"."p_personid" AS "k_person1id", "t95"."k_person2id"
FROM (SELECT "t81"."p_personid"
FROM (SELECT "t79"."p_personid", "t80"."pl_containerplaceid"
FROM (SELECT "p_personid", "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t79"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t80" ON "t79"."p_placeid" = "t80"."pl_placeid") AS "t81"
INNER JOIN (SELECT "t87"."pl_placeid"
FROM (SELECT "t83"."pl_containerplaceid"
FROM (SELECT "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t82"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t83" ON "t82"."p_placeid" = "t83"."pl_placeid") AS "t84"
INNER JOIN (SELECT "pl_placeid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place
WHERE "pl_name" IN ('China', 'India', 'Mexico')) AS "t87" ON "t84"."pl_containerplaceid" = "t87"."pl_placeid"
GROUP BY "t87"."pl_placeid"
HAVING COUNT(*) > 100) AS "t91" ON "t81"."pl_containerplaceid" = "t91"."pl_placeid") AS "t92"
INNER JOIN (SELECT "k_person1id", "k_person2id"
FROM '/mnt/disks/ldbc/parquet/knows.parquet' AS knows
WHERE "k_creationdate" >= 1354147200000 AND "k_creationdate" <= 1362441600000) AS "t95" ON "t92"."p_personid" = "t95"."k_person1id") AS "t96" ON "t78"."k_person2id" = "t96"."k_person1id") AS "t97"
INNER JOIN (SELECT "t111"."p_personid" AS "k_person1id"
FROM (SELECT "t100"."p_personid"
FROM (SELECT "t98"."p_personid", "t99"."pl_containerplaceid"
FROM (SELECT "p_personid", "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t98"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t99" ON "t98"."p_placeid" = "t99"."pl_placeid") AS "t100"
INNER JOIN (SELECT "t106"."pl_placeid"
FROM (SELECT "t102"."pl_containerplaceid"
FROM (SELECT "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t101"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t102" ON "t101"."p_placeid" = "t102"."pl_placeid") AS "t103"
INNER JOIN (SELECT "pl_placeid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place
WHERE "pl_name" IN ('China', 'India', 'Mexico')) AS "t106" ON "t103"."pl_containerplaceid" = "t106"."pl_placeid"
GROUP BY "t106"."pl_placeid"
HAVING COUNT(*) > 100) AS "t110" ON "t100"."pl_containerplaceid" = "t110"."pl_placeid") AS "t111"
INNER JOIN (SELECT "k_person1id", "k_person2id"
FROM '/mnt/disks/ldbc/parquet/knows.parquet' AS knows
WHERE "k_creationdate" >= 1354147200000 AND "k_creationdate" <= 1362441600000) AS "t114" ON "t111"."p_personid" = "t114"."k_person1id") AS "t116" ON "t97"."k_person2id0" = "t116"."k_person1id") AS "t"
UNION ALL
SELECT "t176"."k_person1id" AS "src", "t176"."k_person2id0" AS "dst", 4 AS "w"
FROM (SELECT "t156"."k_person1id", "t156"."k_person2id0", "t175"."k_person2id" AS "k_person2id1"
FROM (SELECT "t137"."k_person1id", "t155"."k_person2id" AS "k_person2id0"
FROM (SELECT "t132"."p_personid" AS "k_person1id", "t135"."k_person2id"
FROM (SELECT "t121"."p_personid"
FROM (SELECT "t119"."p_personid", "t120"."pl_containerplaceid"
FROM (SELECT "p_personid", "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t119"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t120" ON "t119"."p_placeid" = "t120"."pl_placeid") AS "t121"
INNER JOIN (SELECT "t127"."pl_placeid"
FROM (SELECT "t123"."pl_containerplaceid"
FROM (SELECT "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t122"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t123" ON "t122"."p_placeid" = "t123"."pl_placeid") AS "t124"
INNER JOIN (SELECT "pl_placeid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place
WHERE "pl_name" IN ('China', 'India', 'Mexico')) AS "t127" ON "t124"."pl_containerplaceid" = "t127"."pl_placeid"
GROUP BY "t127"."pl_placeid"
HAVING COUNT(*) > 100) AS "t131" ON "t121"."pl_containerplaceid" = "t131"."pl_placeid") AS "t132"
INNER JOIN (SELECT "k_person1id", "k_person2id"
FROM '/mnt/disks/ldbc/parquet/knows.parquet' AS knows
WHERE "k_creationdate" >= 1354147200000 AND "k_creationdate" <= 1362441600000) AS "t135" ON "t132"."p_personid" = "t135"."k_person1id"
WHERE CAST("t132"."p_personid" AS BIGINT) = 28587302322191) AS "t137"
INNER JOIN (SELECT "t151"."p_personid" AS "k_person1id", "t154"."k_person2id"
FROM (SELECT "t140"."p_personid"
FROM (SELECT "t138"."p_personid", "t139"."pl_containerplaceid"
FROM (SELECT "p_personid", "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t138"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t139" ON "t138"."p_placeid" = "t139"."pl_placeid") AS "t140"
INNER JOIN (SELECT "t146"."pl_placeid"
FROM (SELECT "t142"."pl_containerplaceid"
FROM (SELECT "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t141"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t142" ON "t141"."p_placeid" = "t142"."pl_placeid") AS "t143"
INNER JOIN (SELECT "pl_placeid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place
WHERE "pl_name" IN ('China', 'India', 'Mexico')) AS "t146" ON "t143"."pl_containerplaceid" = "t146"."pl_placeid"
GROUP BY "t146"."pl_placeid"
HAVING COUNT(*) > 100) AS "t150" ON "t140"."pl_containerplaceid" = "t150"."pl_placeid") AS "t151"
INNER JOIN (SELECT "k_person1id", "k_person2id"
FROM '/mnt/disks/ldbc/parquet/knows.parquet' AS knows
WHERE "k_creationdate" >= 1354147200000 AND "k_creationdate" <= 1362441600000) AS "t154" ON "t151"."p_personid" = "t154"."k_person1id") AS "t155" ON "t137"."k_person2id" = "t155"."k_person1id") AS "t156"
INNER JOIN (SELECT "t170"."p_personid" AS "k_person1id", "t173"."k_person2id"
FROM (SELECT "t159"."p_personid"
FROM (SELECT "t157"."p_personid", "t158"."pl_containerplaceid"
FROM (SELECT "p_personid", "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t157"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t158" ON "t157"."p_placeid" = "t158"."pl_placeid") AS "t159"
INNER JOIN (SELECT "t165"."pl_placeid"
FROM (SELECT "t161"."pl_containerplaceid"
FROM (SELECT "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t160"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t161" ON "t160"."p_placeid" = "t161"."pl_placeid") AS "t162"
INNER JOIN (SELECT "pl_placeid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place
WHERE "pl_name" IN ('China', 'India', 'Mexico')) AS "t165" ON "t162"."pl_containerplaceid" = "t165"."pl_placeid"
GROUP BY "t165"."pl_placeid"
HAVING COUNT(*) > 100) AS "t169" ON "t159"."pl_containerplaceid" = "t169"."pl_placeid") AS "t170"
INNER JOIN (SELECT "k_person1id", "k_person2id"
FROM '/mnt/disks/ldbc/parquet/knows.parquet' AS knows
WHERE "k_creationdate" >= 1354147200000 AND "k_creationdate" <= 1362441600000) AS "t173" ON "t170"."p_personid" = "t173"."k_person1id") AS "t175" ON "t156"."k_person2id0" = "t175"."k_person1id") AS "t176"
INNER JOIN (SELECT "t190"."p_personid" AS "k_person1id"
FROM (SELECT "t179"."p_personid"
FROM (SELECT "t177"."p_personid", "t178"."pl_containerplaceid"
FROM (SELECT "p_personid", "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t177"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t178" ON "t177"."p_placeid" = "t178"."pl_placeid") AS "t179"
INNER JOIN (SELECT "t185"."pl_placeid"
FROM (SELECT "t181"."pl_containerplaceid"
FROM (SELECT "p_placeid"
FROM '/mnt/disks/ldbc/parquet/person.parquet' AS person) AS "t180"
INNER JOIN (SELECT "pl_placeid", "pl_containerplaceid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place) AS "t181" ON "t180"."p_placeid" = "t181"."pl_placeid") AS "t182"
INNER JOIN (SELECT "pl_placeid"
FROM '/mnt/disks/ldbc/parquet/place.parquet' AS place
WHERE "pl_name" IN ('China', 'India', 'Mexico')) AS "t185" ON "t182"."pl_containerplaceid" = "t185"."pl_placeid"
GROUP BY "t185"."pl_placeid"
HAVING COUNT(*) > 100) AS "t189" ON "t179"."pl_containerplaceid" = "t189"."pl_placeid") AS "t190"
INNER JOIN (SELECT "k_person1id", "k_person2id"
FROM '/mnt/disks/ldbc/parquet/knows.parquet' AS knows
WHERE "k_creationdate" >= 1354147200000 AND "k_creationdate" <= 1362441600000) AS "t193" ON "t190"."p_personid" = "t193"."k_person1id") AS "t195" ON "t176"."k_person2id1" = "t195"."k_person1id") AS "t197"
GROUP BY "src", "dst"

